-- ═══════════════════════════════════════════════════════════════════
-- ECM CORSI — Tabella per la gestione dinamica dei corsi ECM
-- Eseguire questo script nel SQL Editor del progetto Supabase
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS ecm_corsi (
  id          SERIAL PRIMARY KEY,
  cat         TEXT[]  NOT NULL DEFAULT '{}',
  tipo        TEXT    NOT NULL CHECK (tipo IN ('fad', 'residenziale', 'blended')),
  gratuito    BOOLEAN NOT NULL DEFAULT false,
  provider    TEXT    NOT NULL,
  titolo      TEXT    NOT NULL,
  crediti     INTEGER NOT NULL,
  durata      TEXT    NOT NULL,
  costo       TEXT    NOT NULL,
  target      TEXT[]  NOT NULL DEFAULT '{}',
  descrizione TEXT    NOT NULL,
  argomenti   TEXT[]  NOT NULL DEFAULT '{}',
  link        TEXT    NOT NULL,
  data_inizio DATE,
  data_fine   DATE,
  scadenza    TEXT,
  attivo      BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security: chiunque può leggere, solo gli admin possono scrivere
ALTER TABLE ecm_corsi ENABLE ROW LEVEL SECURITY;

CREATE POLICY "ecm_corsi_read_all" ON ecm_corsi
  FOR SELECT USING (true);

CREATE POLICY "ecm_corsi_admin_write" ON ecm_corsi
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND is_admin = true
    )
  );

-- ═══════════════════════════════════════════════════════════════════
-- DATI INIZIALI — 41 corsi ECM per dietisti e professionisti sanitari
-- ═══════════════════════════════════════════════════════════════════

INSERT INTO ecm_corsi (cat, tipo, gratuito, provider, titolo, crediti, durata, costo, target, descrizione, argomenti, link, data_inizio, data_fine, scadenza) VALUES

-- ═══ FAD ═══════════════════════════════════════════════════════════

(ARRAY['nutrizione','fad'], 'fad', false,
 'SINU — Società Italiana di Nutrizione Umana',
 'Nutrizione Clinica Avanzata: dalla Valutazione al Piano Terapeutico',
 12, '8 ore FAD', 'Gratuito per soci SINU / € 60 non soci',
 ARRAY['Dietisti','Medici','Biologi nutrizionisti'],
 'Corso FAD accreditato ECM su valutazione dello stato nutrizionale con strumenti validati (NRS-2002, MNA, MUST), diagnosi di malnutrizione secondo criteri GLIM, NCP (Nutrition Care Process) e formulazione di piani nutrizionali personalizzati.',
 ARRAY['NRS-2002','MNA','GLIM','NCP','Malnutrizione'],
 'https://www.sinu.it/formazione',
 NULL, '2026-12-31', 'Accesso continuativo — verificare su sito SINU'),

(ARRAY['patologie','fad'], 'fad', false,
 'ESPEN — European Society for Clinical Nutrition',
 'ESPEN eLearning: Nutrition in Chronic Diseases',
 8, '6 ore FAD (in inglese)', 'Gratuito per soci ESPEN',
 ARRAY['Dietisti','Medici','Nutrizionisti'],
 'Moduli eLearning della European Society for Clinical Nutrition su nutrizione nelle malattie croniche: diabete, IRC, epatopatia, BPCO, oncologia e malattie cardiovascolari. Basati sulle linee guida ESPEN aggiornate.',
 ARRAY['Diabete','IRC','Oncologia','BPCO','Epatopatie','Linee guida ESPEN'],
 'https://www.espen.org/elearning',
 NULL, NULL, 'Accesso permanente con registrazione ESPEN'),

(ARRAY['pediatria','fad'], 'fad', false,
 'SIP — Società Italiana di Pediatria',
 'Nutrizione Pediatrica: svezzamento, obesità e patologie specifiche',
 10, '8 ore FAD', '€ 50–80',
 ARRAY['Dietisti','Pediatri','MMG','Infermieri pediatrici'],
 'Corso FAD su allattamento al seno (OMS/UNICEF), diversificazione alimentare (BLW e metodo tradizionale), APLV e gestione delle allergie alimentari in età pediatrica, obesità infantile, celiachia e diete speciali in età evolutiva.',
 ARRAY['Allattamento','BLW','Svezzamento','APLV','Obesità infantile','Celiachia'],
 'https://www.sip.it/formazione',
 NULL, '2026-12-31', 'Verificare disponibilità sul sito SIP'),

(ARRAY['nutrizione','fad'], 'fad', true,
 'ISS — Istituto Superiore di Sanità',
 'Sorveglianza Nutrizionale e Indicatori di Salute nella Popolazione Italiana',
 6, '4 ore FAD', 'GRATUITO',
 ARRAY['Tutti i professionisti sanitari'],
 'Corso gratuito ISS su dati epidemiologici della nutrizione italiana, indagini OKkio alla SALUTE (obesità infantile), sistema di sorveglianza PASSI, PASSI d''Argento e i principali indicatori di salute nutrizionale a livello nazionale e regionale.',
 ARRAY['Epidemiologia','OKkio alla SALUTE','PASSI','Sorveglianza','Salute pubblica'],
 'https://www.iss.it/formazione',
 NULL, NULL, 'Accesso libero e continuativo'),

(ARRAY['patologie','fad'], 'fad', false,
 'SID — Società Italiana di Diabetologia',
 'Terapia Medica Nutrizionale nel Diabete Mellito Tipo 1 e Tipo 2',
 10, '8 ore FAD', '€ 40–80',
 ARRAY['Dietisti','Medici diabetologi','MMG','Infermieri'],
 'Linee guida ADA/SID 2024 sulla terapia nutrizionale nel diabete: conteggio dei carboidrati, indice e carico glicemico, dieta mediterranea vs low-carb, gestione della terapia insulinica in relazione all''alimentazione, time-restricted eating e gestione del paziente con complicanze.',
 ARRAY['Diabete T1','Diabete T2','Conteggio CHO','Indice glicemico','Insulina','ADA 2024'],
 'https://www.siditalia.it/formazione',
 NULL, '2026-12-31', 'Verificare su sito SID'),

(ARRAY['nutrizione','fad'], 'fad', true,
 'Humanitas Research Hospital / Fondazione Umberto Veronesi',
 'Alimentazione e Prevenzione dei Tumori: evidenze e raccomandazioni',
 8, '6 ore FAD', 'GRATUITO',
 ARRAY['Tutti i professionisti sanitari'],
 'Corso gratuito sulle evidenze scientifiche sul legame tra alimentazione e rischio oncologico, raccomandazioni WCRF/AIRC aggiornate, nutrizione durante la chemioterapia e radioterapia, cachessia neoplastica, integrazione di omega-3 e arginina nella nutrizione oncologica.',
 ARRAY['Oncologia','Prevenzione tumori','WCRF','Cachessia','Omega-3','Immunonutrizione'],
 'https://www.fondazioneveronesi.it/formazione',
 NULL, NULL, 'Accesso libero — verificare su sito'),

(ARRAY['patologie','fad'], 'fad', false,
 'SINPE — Società Italiana di Nutrizione Parenterale ed Enterale',
 'Nutrizione Artificiale Domiciliare (NAD): indicazioni, gestione e complicanze',
 10, '8 ore FAD', '€ 50–100',
 ARRAY['Dietisti','Infermieri','Medici'],
 'Corso FAD sulla gestione della Nutrizione Artificiale Domiciliare: indicazioni cliniche per NAD enterale e parenterale, selezione del paziente, formule e miscele nutrizionali, dispositivi per accesso vascolare, monitoraggio metabolico e laboratoristico, gestione delle complicanze infettive e metaboliche, aspetti organizzativi e di presa in carico.',
 ARRAY['NAD','NED','Nutrizione enterale domiciliare','Nutrizione parenterale','PICC','Gestione complicanze'],
 'https://www.sinpe.it/formazione',
 NULL, '2026-12-31', 'Verificare su sito SINPE'),

(ARRAY['nutrizione','fad'], 'fad', false,
 'ADI — Associazione Italiana di Dietetica e Nutrizione Clinica',
 'Sarcopenia, Fragilità e Malnutrizione: strategie nutrizionali nell''anziano',
 10, '8 ore FAD', '€ 60–100 (soci/non soci)',
 ARRAY['Dietisti','Geriatri','MMG','Infermieri','Fisioterapisti'],
 'Percorso formativo sulla gestione nutrizionale dell''anziano fragile: criteri EWGSOP2 per la sarcopenia, MNA e valutazione multidimensionale geriatrica, fabbisogni proteici aumentati nell''anziano, supplementazione con proteine e leucina, integrazione di vitamina D, esercizio fisico combinato, nutrizione nel paziente con demenza e disfagia.',
 ARRAY['Sarcopenia','EWGSOP2','MNA','Anziano fragile','Fragilità','Vitamina D','Proteine'],
 'https://www.adiitalia.net/formazione',
 NULL, '2026-12-31', 'Verificare disponibilità su sito ADI Italia'),

(ARRAY['patologie','fad'], 'fad', true,
 'ISS — Istituto Superiore di Sanità / Ministero della Salute',
 'Allergie e Intolleranze Alimentari: diagnosi, gestione e comunicazione al paziente',
 6, '5 ore FAD', 'GRATUITO',
 ARRAY['Tutti i professionisti sanitari'],
 'Corso gratuito su allergie IgE-mediate e non IgE-mediate, differenze con le intolleranze alimentari, APLV, allergia alle arachidi, celiachia e sensibilità al glutine non celiaca (SGNC), intolleranza al lattosio, FODMAP e IBS, gestione dell''etichettatura degli allergeni e comunicazione corretta al paziente.',
 ARRAY['Allergie alimentari','APLV','Celiachia','SGNC','Lattosio','FODMAP','IBS','Intolleranze'],
 'https://www.iss.it/formazione',
 NULL, NULL, 'Accesso libero e continuativo'),

(ARRAY['nutrizione','fad'], 'fad', false,
 'SINU — Società Italiana di Nutrizione Umana',
 'Nutrizione Sostenibile e Planetary Health Diet: la dieta del futuro',
 8, '6 ore FAD', 'Gratuito per soci SINU / € 50 non soci',
 ARRAY['Dietisti','Medici','Biologi nutrizionisti','Professionisti della salute'],
 'Corso FAD sui principi della Planetary Health Diet (Commissione EAT-Lancet), impatto ambientale dell''alimentazione (impronta di carbonio e idrica), diete plant-based e salute, riduzione degli sprechi alimentari, strategie pratiche per pazienti e comunità.',
 ARRAY['Planetary Health Diet','Sostenibilità','Plant-based','EAT-Lancet','Impronta carbonica','Dieta mediterranea'],
 'https://www.sinu.it/formazione',
 NULL, '2026-12-31', 'Accesso continuativo — verificare su sito SINU'),

(ARRAY['nutrizione','fad'], 'fad', false,
 'ADI — Associazione Italiana di Dietetica e Nutrizione Clinica',
 'Nutrizione nei Disturbi del Comportamento Alimentare (DCA): approccio clinico integrato',
 10, '8 ore FAD', '€ 70–120 (soci/non soci)',
 ARRAY['Dietisti','Psicologi','Medici','Infermieri'],
 'Percorso FAD sulla gestione nutrizionale nei DCA: anoressia nervosa, bulimia nervosa, BED (Binge Eating Disorder), ARFID. Valutazione e ripristino nutrizionale nel paziente anoressico (refeeding syndrome), piano nutrizionale personalizzato, alleanza terapeutica e approccio multidisciplinare.',
 ARRAY['DCA','Anoressia nervosa','Bulimia','BED','ARFID','Refeeding syndrome','Approccio multidisciplinare'],
 'https://www.adiitalia.net/formazione',
 NULL, '2026-12-31', 'Verificare disponibilità su sito ADI Italia'),

(ARRAY['patologie','fad'], 'fad', false,
 'SIC / SISA — Società Italiana di Cardiologia',
 'Nutrizione e Rischio Cardiovascolare: dalla prevenzione alla gestione terapeutica',
 8, '6 ore FAD', '€ 40–70',
 ARRAY['Dietisti','Cardiologi','MMG','Infermieri'],
 'Corso FAD su linee guida ESC 2023 per la prevenzione cardiovascolare tramite stile di vita, dieta mediterranea e riduzione del rischio CV, gestione dell''ipercolesterolemia attraverso la dieta, approccio nutrizionale all''ipertensione arteriosa (dieta DASH), gestione dell''insufficienza cardiaca.',
 ARRAY['Rischio cardiovascolare','Dieta DASH','Ipercolesterolemia','Ipertensione','ESC 2023','Prevenzione CV'],
 'https://www.cardioitalia.net/formazione',
 NULL, '2026-12-31', 'Verificare su sito SIC'),

(ARRAY['nutrizione','fad'], 'fad', false,
 'FAND — Federazione Associazioni Nazionali Dietisti',
 'Il Dietista nel Team Multiprofessionale: ruolo, responsabilità e NCP',
 8, '6 ore FAD', '€ 50–80 (soci/non soci)',
 ARRAY['Dietisti'],
 'Corso FAD sul ruolo professionale del dietista nel team multiprofessionale sanitario, applicazione del Nutrition Care Process (NCP/NCPT) nella pratica clinica, documentazione nutrizionale e terminologia standardizzata, responsabilità professionale e collaborazione interprofessionale. Include casi clinici interattivi.',
 ARRAY['NCP','NCPT','Team multiprofessionale','Documentazione','Ruolo professionale dietista','FNABI'],
 'https://www.andid.it/formazione',
 NULL, '2026-12-31', 'Accesso continuativo — verificare su sito ANDID'),

(ARRAY['nutrizione','fad'], 'fad', true,
 'CREA — Centro di Ricerca Alimenti e Nutrizione',
 'Linee Guida per una Sana Alimentazione Italiana 2024: aggiornamento e applicazioni pratiche',
 6, '4 ore FAD', 'GRATUITO',
 ARRAY['Tutti i professionisti sanitari'],
 'Corso gratuito basato sulle nuove Linee Guida CREA 2024 per una sana alimentazione nella popolazione italiana: revisione delle porzioni e frequenze consigliate, aggiornamenti su legumi, pesce azzurro, frutta secca, sale e zuccheri, indicazioni specifiche per fasce di età.',
 ARRAY['Linee guida CREA','Alimentazione italiana','Porzioni','Frequenza alimentare','Prevenzione','LARN'],
 'https://www.crea.gov.it/alimenti-e-nutrizione',
 NULL, NULL, 'Accesso libero e continuativo'),

(ARRAY['patologie','fad'], 'fad', false,
 'ADI — Associazione Italiana di Dietetica e Nutrizione Clinica',
 'Nutrizione in Oncologia: screening, valutazione e supporto nutrizionale',
 12, '10 ore FAD', '€ 80–140 (soci/non soci)',
 ARRAY['Dietisti','Oncologi','Infermieri oncologici','Medici'],
 'Percorso FAD completo sulla nutrizione oncologica: screening nutrizionale nel paziente oncologico (MST, MUST, PG-SGA), valutazione della composizione corporea, gestione degli effetti collaterali della chemio e radioterapia (mucosite, nausea, xerostomia), cachessia neoplastica e sarcopenia, supplementazione nutrizionale orale e nutrizione artificiale.',
 ARRAY['Oncologia','Cachessia','PG-SGA','MST','Chemioterapia','Radioterapia','Mucosite','Sarcopenia oncologica'],
 'https://www.adiitalia.net/formazione',
 NULL, '2026-12-31', 'Verificare disponibilità su sito ADI Italia'),

(ARRAY['patologie','fad'], 'fad', false,
 'SIGE — Società Italiana di Gastroenterologia ed Endoscopia',
 'Nutrizione nelle Malattie Infiammatorie Intestinali (IBD): Crohn e Colite Ulcerosa',
 8, '6 ore FAD', '€ 50–90',
 ARRAY['Dietisti','Gastroenterologi','Medici','Infermieri'],
 'Corso FAD su valutazione e gestione nutrizionale nelle IBD: malnutrizione in Crohn e colite ulcerosa, nutrizione enterale esclusiva (NEE) come terapia d''induzione nel Crohn, gestione del paziente con stomia, integrazione di probiotici e prebiotici nelle IBD.',
 ARRAY['Malattia di Crohn','Colite ulcerosa','IBD','NEE','Stomia','Probiotici','Prebiotici','Malnutrizione IBD'],
 'https://www.sige.it/formazione',
 NULL, '2026-12-31', 'Verificare su sito SIGE'),

-- ═══ BLENDED ════════════════════════════════════════════════════════

(ARRAY['patologie','fad'], 'blended', false,
 'ADI — Associazione Italiana di Dietetica e Nutrizione Clinica',
 'Nutrizione Enterale e Parenterale: Gestione Pratica in Ospedale e a Domicilio',
 14, '10 ore FAD + 2 ore residenziale', '€ 120–200 (soci/non soci)',
 ARRAY['Dietisti','Infermieri','Medici'],
 'Percorso formativo completo sulla nutrizione artificiale clinica: indicazioni e controindicazioni, accessi enterali (SNG, PEG, digiunostomia), miscele standard e modulari, nutrizione parenterale totale (NPT) e periferica, monitoraggio, NED domiciliare e gestione delle complicanze metaboliche.',
 ARRAY['Nutrizione enterale','Nutrizione parenterale','PEG','NPT','NED','Complicanze'],
 'https://www.adiitalia.net/formazione',
 NULL, '2026-12-31', 'Verificare disponibilità su sito ADI Italia'),

(ARRAY['nutrizione','fad'], 'blended', false,
 'SINU — Società Italiana di Nutrizione Umana',
 'Il Caso Clinico in Nutrizione: percorso interattivo di valutazione e pianificazione',
 12, '8 ore FAD + 2 ore interazione online', '€ 70–100',
 ARRAY['Dietisti','Medici','Biologi nutrizionisti'],
 'Corso blended con simulazioni di casi clinici reali in diverse aree della nutrizione clinica: malnutrizione ospedaliera, paziente critico in ICU, nutrizione pre e post operatoria, insufficienza renale cronica, epatopatia avanzata, obesità e sindrome metabolica. Include sessioni di discussione online con esperti.',
 ARRAY['Casi clinici','Malnutrizione ospedaliera','ICU','Chirurgia','Sindrome metabolica','Valutazione nutrizionale'],
 'https://www.sinu.it/formazione',
 NULL, '2026-12-31', 'Accesso continuativo — verificare su sito SINU'),

-- ═══ RESIDENZIALE ════════════════════════════════════════════════════

(ARRAY['nutrizione','residenziale'], 'residenziale', false,
 'ADI — Associazione Italiana di Dietetica e Nutrizione Clinica',
 'ADI Congress 2026 — Annual Meeting della Nutrizione Clinica Italiana',
 18, '3 giorni (22–24 maggio 2026)', '€ 250–450 (soci/non soci)',
 ARRAY['Dietisti','Medici','Biologi nutrizionisti','Infermieri','Professionisti sanitari'],
 'Il principale congresso italiano di nutrizione clinica. Aggiornamento multidisciplinare su nutrizione ospedaliera e domiciliare, linee guida ESPEN/SINPE, innovazioni in nutrizione artificiale, oncologica, geriatrica e pediatrica. Sessioni parallele, workshop pratici, letture magistrali da esperti internazionali.',
 ARRAY['Nutrizione clinica','ESPEN','Congresso ADI','Nutrizione artificiale','Aggiornamento multidisciplinare'],
 'https://www.adiitalia.net/congresso',
 '2026-05-22', '2026-05-24', 'Iscrizioni aperte — verificare su sito ADI'),

(ARRAY['nutrizione','sport','residenziale'], 'residenziale', false,
 'ANDID — Associazione Nazionale Dietisti',
 'Nutrizione Sportiva e Performance Atletica: dalla Teoria al Campo',
 10, '2 giorni (29–30 maggio 2026)', '€ 150–250 (soci/non soci)',
 ARRAY['Dietisti','Medici sportivi','Fisioterapisti'],
 'Workshop residenziale sulla nutrizione nello sport: fabbisogni energetici e macronutrienti per atleti, carboloading e strategie pre-gara, integrazione sportiva evidence-based (creatina, caffeina, beta-alanina, nitrati), RED-S (Relative Energy Deficiency in Sport) e Female Athlete Triad.',
 ARRAY['Nutrizione sportiva','Carboloading','RED-S','Integrazione sportiva','Creatina','Caffeina','Performance atletica'],
 'https://www.andid.it/formazione',
 '2026-05-29', '2026-05-30', 'Iscrizioni aperte — verificare calendario ANDID'),

(ARRAY['pediatria','residenziale'], 'residenziale', false,
 'SIPPS — Società Italiana di Prevenzione e Igiene Pediatrica',
 'Svezzamento Guidato dal Bambino (BLW) e Alimentazione Complementare 0–3 Anni',
 8, '1 giorno (10 maggio 2026)', '€ 90–150',
 ARRAY['Pediatri','Dietisti','Ostetriche','MMG'],
 'Workshop pratico sul Baby-Led Weaning: basi teoriche e pratiche, sicurezza alimentare e rischio soffocamento, prevenzione delle allergie con introduzione precoce degli allergeni (LEAP study), educazione alimentare responsiva, linee guida WHO/ESPGHAN 2024 per l''allattamento e lo svezzamento.',
 ARRAY['BLW','Prevenzione allergie','ESPGHAN','WHO','Alimentazione complementare','LEAP study'],
 'https://www.sipps.it',
 '2026-05-10', '2026-05-10', 'Iscrizioni aperte — verificare calendario SIPPS'),

(ARRAY['patologie','residenziale'], 'residenziale', false,
 'AISF — Associazione Italiana Studio Fegato',
 'Malattie Epatiche e Nutrizione: NAFLD/MAFLD, Cirrosi e Trapianto di Fegato',
 12, '2 giorni (12–13 giugno 2026)', '€ 150–250',
 ARRAY['Dietisti','Epatologi','Gastroenterologi','Medici','Infermieri'],
 'Corso residenziale sulla gestione nutrizionale delle malattie epatiche: NAFLD/MAFLD e dieta a basso contenuto di fruttosio/zuccheri, sarcopenia nella cirrosi epatica, prevenzione e trattamento dell''encefalopatia epatica con BCAA, nutrizione nel post-trapianto epatico, gestione della ritenzione idrica e ascite con dieta iposodica.',
 ARRAY['NAFLD','MAFLD','Cirrosi','Encefalopatia epatica','BCAA','Trapianto fegato','Ascite','Sarcopenia epatica'],
 'https://www.webaisf.org',
 '2026-06-12', '2026-06-13', 'Iscrizioni aperte — verificare su sito AISF'),

(ARRAY['patologie','residenziale'], 'residenziale', false,
 'ANDID — Associazione Nazionale Dietisti / GdL Disfagia',
 'Disfagia e Texture Modified Foods: valutazione e gestione nutrizionale',
 10, '2 giorni (19–20 giugno 2026)', '€ 150–240 (soci/non soci)',
 ARRAY['Dietisti','Logopedisti','Medici','Infermieri','Terapisti occupazionali'],
 'Corso residenziale sulla valutazione e gestione della disfagia: classificazione IDDSI, texture modified foods (TMF) e fluidi addensati, bedside swallowing assessment, videofluoroscopia e FEES, strategie di compensazione posturale, gestione nutrizionale del paziente disfagico neurologico (post-ictus, SLA, Parkinson).',
 ARRAY['Disfagia','IDDSI','Texture modified foods','Addensanti','Videofluoroscopia','FEES','SLA','Ictus','Parkinson'],
 'https://www.andid.it/formazione',
 '2026-06-19', '2026-06-20', 'Iscrizioni aperte — verificare calendario ANDID'),

(ARRAY['pediatria','residenziale'], 'residenziale', false,
 'SINUPE — Società Italiana di Nutrizione Pediatrica',
 'Obesità Infantile e Adolescenziale: dalla Prevenzione al Trattamento Multidisciplinare',
 12, '2 giorni (5–6 giugno 2026)', '€ 180–280',
 ARRAY['Pediatri','Dietisti','Psicologi','MMG','Endocrinologi'],
 'Approccio integrato e multidisciplinare all''obesità infantile e adolescenziale: strumenti di diagnosi precoce (BMI/età, circonferenza addominale), intervento nutrizionale per fasce d''età, aspetti psicologici e familiari, comorbilità metaboliche (insulino-resistenza, NAFLD, ipertensione) e indicazioni al trattamento farmacologico in adolescenza.',
 ARRAY['Obesità pediatrica','BMI','Insulino-resistenza','NAFLD','Approccio multidisciplinare','Adolescenti'],
 'https://www.sinupe.it',
 '2026-06-05', '2026-06-06', 'Iscrizioni aperte — verificare su sito SINUPE'),

(ARRAY['patologie','residenziale'], 'residenziale', false,
 'SIGE — Società Italiana di Gastroenterologia',
 'Nutrizione nelle Malattie Gastrointestinali: dalla Celiachia alla IBS',
 10, '2 giorni (3–4 luglio 2026)', '€ 160–260',
 ARRAY['Dietisti','Gastroenterologi','Medici internisti','Infermieri'],
 'Corso residenziale sulla nutrizione nelle principali patologie gastrointestinali: celiachia e dieta senza glutine (gestione della contaminazione, etichettatura), SGNC, IBS e dieta a basso contenuto di FODMAP (protocollo Monash), SIBO, reflusso gastroesofageo (GERD), malabsorzione e gestione nutrizionale post-chirurgia bariatrica.',
 ARRAY['Celiachia','Dieta senza glutine','SGNC','IBS','FODMAP','SIBO','GERD','Chirurgia bariatrica','Malabsorzione'],
 'https://www.sige.it/formazione',
 '2026-07-03', '2026-07-04', 'Iscrizioni aperte — verificare su sito SIGE'),

(ARRAY['patologie','residenziale'], 'residenziale', false,
 'Federazione COMLAS / ADI Italia',
 'Nutrizione nell''Insufficienza Renale Cronica: dalla Teoria alla Pratica Clinica',
 10, '1 giorno (19 settembre 2026)', '€ 100–180',
 ARRAY['Dietisti','Medici nefrologi','Infermieri'],
 'Corso pratico sulla gestione nutrizionale del paziente con IRC: restrizione proteica (0.6–0.8 g/kg), gestione di potassio e fosforo, lisciviazione delle verdure, paziente dialitico (emodialitico e peritoneale), CKD-MBD e osteopatia renale, calcolo del fabbisogno con eGFR, monitoraggio biochimico e nutrizionale.',
 ARRAY['IRC','CKD','Dialisi','Potassio','Fosforo','Proteine','Lisciviazione','CKD-MBD'],
 'https://www.ecm.salute.gov.it',
 '2026-09-19', '2026-09-19', 'Iscrizioni aperte — verificare calendario ECM regionale'),

(ARRAY['patologie','residenziale'], 'residenziale', false,
 'ADI — Associazione Italiana di Dietetica e Nutrizione Clinica',
 'Nutrizione Oncologica Update 2026: nuove evidenze e strategie pratiche',
 14, '2 giorni (11–12 settembre 2026)', '€ 200–350 (soci/non soci)',
 ARRAY['Dietisti','Oncologi','Infermieri oncologici','Medici'],
 'Congresso residenziale di aggiornamento in nutrizione oncologica: nuove linee guida ESPEN 2024/2025, immunonutrizione pre-operatoria (ERAS protocol), gestione della cachessia con anamorelina, nutrizione e immunoterapia, microbiota e risposta ai farmaci oncologici.',
 ARRAY['Oncologia','Cachessia','ESPEN','ERAS','Immunonutrizione','Anamorelina','Immunoterapia','Microbiota oncologico'],
 'https://www.adiitalia.net/congresso',
 '2026-09-11', '2026-09-12', 'Iscrizioni aperte — verificare su sito ADI'),

(ARRAY['patologie','residenziale'], 'residenziale', false,
 'SID — Società Italiana di Diabetologia',
 'Nutrizione nel Diabete Gestazionale e in Gravidanza: strategie pratiche 2026',
 8, '1 giorno (25 settembre 2026)', '€ 80–150',
 ARRAY['Dietisti','Ginecologi','Diabetologi','Ostetriche','MMG'],
 'Corso residenziale sulla nutrizione in gravidanza e diabete gestazionale: nuovi criteri diagnostici IADPSG, terapia medica nutrizionale nel GDM (conteggio carboidrati, indice glicemico), obiettivi glicemici in gravidanza, gestione del peso gestazionale, fabbisogni di omega-3, DHA, folati, ferro e vitamina D.',
 ARRAY['Diabete gestazionale','GDM','IADPSG','Gravidanza','DHA','Folati','Gestione glicemica'],
 'https://www.siditalia.it/formazione',
 '2026-09-25', '2026-09-25', 'Iscrizioni aperte — verificare su sito SID'),

(ARRAY['nutrizione','residenziale'], 'residenziale', false,
 'SINU — Società Italiana di Nutrizione Umana',
 'Microbiota Intestinale e Nutrizione: evidenze cliniche e applicazioni pratiche',
 12, '2 giorni (9–10 ottobre 2026)', '€ 180–300',
 ARRAY['Dietisti','Medici','Biologi','Gastroenterologi'],
 'Congresso residenziale sulle più recenti evidenze scientifiche sul microbiota intestinale: composizione e funzione del microbioma umano, impatto della dieta sulla diversità microbiotica, probiotici e prebiotici evidence-based, trapianto di microbiota fecale (FMT), microbiota in IBD, diabete, obesità e salute mentale (asse intestino-cervello).',
 ARRAY['Microbiota intestinale','Probiotici','Prebiotici','FMT','Asse intestino-cervello','Disbiosi','Psicobiotici'],
 'https://www.sinu.it/formazione',
 '2026-10-09', '2026-10-10', 'Iscrizioni aperte — verificare su sito SINU'),

(ARRAY['nutrizione','residenziale'], 'residenziale', false,
 'ANDID — Associazione Nazionale Dietisti',
 '44° Congresso Nazionale ANDID 2026 — Nutrizione, Innovazione e Futuro della Dietetica',
 16, '3 giorni (15–17 ottobre 2026)', '€ 180–380 (soci/non soci)',
 ARRAY['Dietisti'],
 'Il principale evento formativo nazionale per i dietisti italiani. Aggiornamento su tutte le aree della nutrizione clinica con relatori italiani e internazionali. Include sessioni plenarie, workshop paralleli, poster scientifici, symposia industriali e networking professionale.',
 ARRAY['Nutrizione clinica','NCP','Innovazione','Ricerca','Network professionale','ANDID 2026'],
 'https://www.andid.it/congresso',
 '2026-10-15', '2026-10-17', 'Iscrizioni aperte fino a settembre 2026'),

(ARRAY['nutrizione','residenziale'], 'residenziale', false,
 'ANDID — Associazione Nazionale Dietisti',
 'La Comunicazione Efficace con il Paziente: Counseling Motivazionale in Dietetica',
 8, '1 giorno (14 novembre 2026)', '€ 100–180 (soci/non soci)',
 ARRAY['Dietisti','Nutrizionisti'],
 'Workshop pratico sul counseling motivazionale (Motivational Interviewing) applicato alla dietetica: tecniche di comunicazione empatica, gestione della resistenza al cambiamento, tecniche SMART per la definizione degli obiettivi, gestione del paziente obeso e aderenza alla terapia dietetica. Laboratorio pratico con role-playing.',
 ARRAY['Counseling','Motivational Interviewing','Comunicazione','Aderenza terapeutica','Psicologia alimentazione','Role-playing'],
 'https://www.andid.it/formazione',
 '2026-11-14', '2026-11-14', 'Iscrizioni aperte — verificare calendario ANDID regionale'),

(ARRAY['pediatria','residenziale'], 'residenziale', false,
 'SINUPE — Società Italiana di Nutrizione Pediatrica',
 'Nutrizione Neonatale e del Prematuro: dalle Linee Guida alla Pratica di Reparto',
 10, '2 giorni (6–7 novembre 2026)', '€ 160–260',
 ARRAY['Dietisti','Neonatologi','Ostetriche','Infermieri neonatali','Pediatri'],
 'Corso residenziale sulla nutrizione neonatale: latte materno e fortification nel prematuro, formule per prematuri e neonati a termine, nutrizione parenterale in TIN, valutazione della crescita neonatale con curve WHO, allattamento al seno difficoltoso e supporto alla madre, nutrizione enterale minima e avanzamento nel grande prematuro.',
 ARRAY['Nutrizione neonatale','Prematuro','TIN','Latte materno','Fortification','Curva di crescita WHO','Allattamento'],
 'https://www.sinupe.it',
 '2026-11-06', '2026-11-07', 'Iscrizioni aperte — verificare su sito SINUPE');

-- ═══════════════════════════════════════════════════════════════════
-- NUOVI CORSI (IDs 33–41) — aggiornamento 2026
-- ═══════════════════════════════════════════════════════════════════

INSERT INTO ecm_corsi (cat, tipo, gratuito, provider, titolo, crediti, durata, costo, target, descrizione, argomenti, link, data_inizio, data_fine, scadenza) VALUES

(ARRAY['patologie','fad'], 'fad', false,
 'ADI / SINPE — Nutrizione Artificiale',
 'Nutrizione nel Paziente Critico in ICU: dalle Linee Guida alla Pratica',
 12, '10 ore FAD', '€ 80–140 (soci/non soci)',
 ARRAY['Dietisti','Medici intensivisti','Infermieri di area critica'],
 'Corso FAD sulla gestione nutrizionale del paziente critico in Terapia Intensiva: timing della nutrizione enterale precoce, protocolli ESPEN 2023 per ICU, gestione della nutrizione nel paziente con instabilità emodinamica, monitoraggio della tolleranza enterale, nutrizione nel paziente con ARDS e insufficienza multiorgano.',
 ARRAY['ICU','Terapia intensiva','Nutrizione enterale precoce','ARDS','ESPEN ICU','Instabilità emodinamica','Insufficienza multiorgano'],
 'https://www.sinpe.it/formazione',
 NULL, '2026-12-31', 'Verificare su sito SINPE'),

(ARRAY['nutrizione','fad'], 'fad', false,
 'SINU — Società Italiana di Nutrizione Umana',
 'Interazioni Farmaco-Nutriente: dal Warfarin agli Inibitori di Pompa',
 8, '6 ore FAD', 'Gratuito per soci SINU / € 50 non soci',
 ARRAY['Dietisti','Farmacisti','Medici','Infermieri'],
 'Percorso FAD sulle principali interazioni clinicamente rilevanti tra farmaci e nutrienti: anticoagulanti orali (warfarin) e vitamina K, MAO-inibitori e tiramina, farmaci antiretrovirali e alimenti, interazioni con pompelmo, nutrizione enterale e assorbimento dei farmaci, gestione pratica nella prescrizione del piano alimentare.',
 ARRAY['Warfarin','Vitamina K','Interazioni farmaco-nutriente','MAO-inibitori','Tiramina','Nutrizione enterale','Pompelmo'],
 'https://www.sinu.it/formazione',
 NULL, '2026-12-31', 'Accesso continuativo — verificare su sito SINU'),

(ARRAY['patologie','fad'], 'fad', false,
 'ADI — Associazione Italiana di Dietetica e Nutrizione Clinica',
 'Nutrizione nella Chirurgia Bariatrica: Percorso Nutrizionale Pre e Post-operatorio',
 10, '8 ore FAD', '€ 70–120 (soci/non soci)',
 ARRAY['Dietisti','Chirurghi bariatrici','Medici endocrinologi'],
 'Corso FAD sulla gestione nutrizionale del paziente bariatrico: valutazione preoperatoria, dieta pre-operatoria iperproteica ipocalorica, gestione post-operatoria per bypass gastrico e sleeve gastrectomy, supplementazione di micronutrienti (ferro, B12, calcio, vitamina D, tiamina), dumping syndrome e prevenzione delle carenze a lungo termine.',
 ARRAY['Chirurgia bariatrica','Bypass gastrico','Sleeve gastrectomy','Dumping syndrome','Carenze micronutrienti','Supplementazione','Vitamina B12'],
 'https://www.adiitalia.net/formazione',
 NULL, '2026-12-31', 'Verificare disponibilità su sito ADI Italia'),

(ARRAY['patologie','fad'], 'fad', false,
 'AIC — Associazione Italiana Celiachia',
 'Celiachia e Sensibilità al Glutine: dalla Diagnosi alla Gestione Dietetica Ottimale',
 8, '6 ore FAD', '€ 40–70',
 ARRAY['Dietisti','Gastroenterologi','MMG','Infermieri'],
 'Corso FAD aggiornato sulla celiachia e condizioni correlate: nuovi criteri diagnostici ESPGHAN 2020, differenze tra celiachia, SGNC e allergia al frumento, dieta senza glutine in pratica (etichettatura, contaminazione crociata), rischio di carenze nella DSG, follow-up a lungo termine e complicanze.',
 ARRAY['Celiachia','SGNC','Dieta senza glutine','ESPGHAN','Etichettatura','Contaminazione crociata','Anti-tTG','EMA'],
 'https://www.celiachia.it/formazione',
 NULL, '2026-12-31', 'Verificare disponibilità su sito AIC'),

(ARRAY['nutrizione','fad'], 'fad', false,
 'SIN — Società Italiana di Neonatologia / SID',
 'Nutrizione e Integrazione in Gravidanza: Micronutrienti, DHA, Folati e Oltre',
 10, '8 ore FAD', '€ 60–100',
 ARRAY['Dietisti','Ginecologi','Ostetriche','MMG'],
 'Percorso FAD sulla nutrizione ottimale in gravidanza e allattamento: fabbisogni calorici e proteici aumentati, supplementazione raccomandata (acido folico, ferro, iodio, vitamina D, DHA, zinco, B12), gestione del peso gestazionale secondo IOM, diete speciali in gravidanza, alimenti da evitare, nausea e vomito gravidici.',
 ARRAY['Gravidanza','Acido folico','DHA','Ferro in gravidanza','Vitamina D','Iodio','Peso gestazionale','Allattamento','Nausea gravidica'],
 'https://www.siditalia.it/formazione',
 NULL, '2026-12-31', 'Verificare disponibilità su sito SID'),

(ARRAY['nutrizione','fad'], 'fad', false,
 'ANDID — Associazione Nazionale Dietisti',
 'Counseling Nutrizionale Motivazionale: Tecniche e Strumenti per il Dietista',
 8, '6 ore FAD', '€ 50–80 (soci/non soci)',
 ARRAY['Dietisti','Nutrizionisti'],
 'Corso FAD sulle tecniche di counseling motivazionale applicate alla dietetica: principi del Motivational Interviewing (MI), ruolo dei processi cognitivi nel cambiamento delle abitudini alimentari, tecniche SMART per la definizione degli obiettivi, gestione dell''ambivalenza, ascolto attivo e comunicazione empatica, educazione terapeutica strutturata.',
 ARRAY['Motivational Interviewing','Counseling','Cambiamento comportamentale','SMART','Ascolto attivo','Educazione terapeutica','Aderenza'],
 'https://www.andid.it/formazione',
 NULL, '2026-12-31', 'Accesso continuativo — verificare su sito ANDID'),

(ARRAY['nutrizione','fad'], 'fad', false,
 'ANDID — Associazione Nazionale Dietisti',
 'Dietetica Digitale e Telemedicina: Strumenti Innovativi per il Dietista',
 6, '5 ore FAD', '€ 40–60 (soci/non soci)',
 ARRAY['Dietisti','Nutrizionisti'],
 'Corso FAD sulla trasformazione digitale della professione dietistica: software e app per la pianificazione alimentare e il monitoraggio del paziente, telemedicina e teleconsulto nutrizionale, wearables e sensori CGM nella gestione del diabete, intelligenza artificiale applicata alla nutrizione, aspetti etici e privacy (GDPR).',
 ARRAY['Telemedicina','App nutrizionali','CGM','Intelligenza artificiale','GDPR','Telemonitoraggio','Digital health','Wearables'],
 'https://www.andid.it/formazione',
 NULL, '2026-12-31', 'Accesso continuativo — verificare su sito ANDID'),

(ARRAY['nutrizione','residenziale'], 'residenziale', false,
 'SINPE — Società Italiana di Nutrizione Parenterale ed Enterale',
 'Congresso Nazionale SINPE 2026 — Nutrizione Artificiale: Innovazioni e Nuove LG',
 16, '2 giorni (27–28 novembre 2026)', '€ 200–380 (soci/non soci)',
 ARRAY['Dietisti','Medici','Infermieri','Farmacisti'],
 'Congresso annuale SINPE: aggiornamento su nutrizione enterale e parenterale, nuove linee guida ESPEN/SINPE 2025-2026, nutrizione artificiale domiciliare (NAD/NPD), gestione delle complicanze, innovazioni nelle miscele nutrizionali e nei dispositivi per accesso enterale e vascolare. Workshop pratici con simulatori.',
 ARRAY['Nutrizione artificiale','SINPE','ESPEN','NAD','NPD','Nutrizione enterale','Nutrizione parenterale','Workshop'],
 'https://www.sinpe.it/congresso',
 '2026-11-27', '2026-11-28', 'Iscrizioni aperte — verificare su sito SINPE'),

(ARRAY['patologie','residenziale'], 'residenziale', false,
 'SIN — Società Italiana di Nefrologia',
 'Congresso SIN 2026 — Gestione Nutrizionale Avanzata del Paziente Nefropatico',
 12, '2 giorni (6–7 novembre 2026)', '€ 150–280',
 ARRAY['Dietisti','Nefrologi','Infermieri nefrologici'],
 'Sessioni dedicate alla nutrizione nel congresso SIN 2026: nuove linee guida KDIGO/ESPEN nella CKD, nutrizione nel trapianto renale, sindrome di malnutrizione-infiammazione (MIS), calcio e metabolismo osseo nella CKD-MBD, innovazioni nella dialisi e impatto nutrizionale.',
 ARRAY['IRC','CKD','Dialisi peritoneale','Emodialisi','KDIGO','Trapianto renale','MIS','CKD-MBD'],
 'https://www.sin-italy.org',
 '2026-11-06', '2026-11-07', 'Iscrizioni aperte — verificare su sito SIN');
