RICETTE_DB=[
{id:'tpl_1021',nome:'Pasta al pesto genovese',nome_en:'Pasta with Genoese pesto',categoria:'Primo piatto',porzioni:4,
note:'Frullare basilico, pinoli, aglio, pecorino, parmigiano e olio a freddo. Cuocere le trofie in acqua salata. Scolare al dente, mantecare con il pesto aggiungendo un cucchiaio di acqua di cottura.',
note_en:'Blend basil, pine nuts, garlic, pecorino, parmesan and oil cold. Cook trofie in salted water. Drain al dente, toss with pesto adding a spoonful of cooking water.',
ingredienti:[{nome:'Trofie',qt:'320g'},{nome:'Basilico fresco',qt:'60g'},{nome:'Pinoli',qt:'40g'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Parmigiano grattugiato',qt:'40g'},{nome:'Pecorino grattugiato',qt:'20g'},{nome:'Olio extravergine',qt:'80ml'}],
_dbEntry:{n:'Pasta al pesto genovese (ricetta)',c:'Ricette',src:'RICETTE',k:420,p:13,gs:3,g:18,z:2,ch:55,fi:2.5,ca:120,fe:2,mg:40,k2:200,na:180,zn:1.2,fo:30,se:8,col:8}},

{id:'tpl_1022',nome:'Pasta e fagioli napoletana',nome_en:'Neapolitan pasta and beans',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere aglio, rosmarino e pomodoro. Aggiungere fagioli borlotti lessati e brodo. Cuocere 15 minuti. Aggiungere pasta mista corta e cuocere al dente. Finire con olio crudo e pepe.',
note_en:'Sauté garlic, rosemary and tomato. Add boiled borlotti beans and stock. Cook 15 minutes. Add mixed short pasta and cook al dente. Finish with raw oil and pepper.',
ingredienti:[{nome:'Fagioli borlotti cotti',qt:'400g'},{nome:'Pasta mista',qt:'200g'},{nome:'Pomodori pelati',qt:'200g'},{nome:'Aglio',qt:'3 spicchi'},{nome:'Rosmarino',qt:'1 rametto'},{nome:'Olio extravergine',qt:'40ml'},{nome:'Brodo vegetale',qt:'500ml'}],
_dbEntry:{n:'Pasta e fagioli napoletana (ricetta)',c:'Ricette',src:'RICETTE',k:320,p:14,gs:1,g:7,z:3,ch:52,fi:9,ca:70,fe:3.5,mg:60,k2:580,na:320,zn:1.5,fo:120,se:6,col:0}},

{id:'tpl_1023',nome:'Risotto ai funghi porcini',nome_en:'Porcini mushroom risotto',categoria:'Primo piatto',porzioni:4,
note:'Ammollare i porcini secchi 30 minuti. Soffriggere scalogno, aggiungere riso e tostare. Sfumare con vino bianco. Aggiungere brodo caldo mestolo per mestolo. Aggiungere i porcini ammollati. Mantecare con burro e parmigiano.',
note_en:'Soak dried porcini 30 minutes. Sauté shallot, add rice and toast. Deglaze with white wine. Add hot stock ladle by ladle. Add soaked porcini. Stir in butter and parmesan.',
ingredienti:[{nome:'Riso Carnaroli',qt:'320g'},{nome:'Porcini secchi',qt:'30g'},{nome:'Scalogno',qt:'2'},{nome:'Vino bianco',qt:'100ml'},{nome:'Burro',qt:'40g'},{nome:'Parmigiano grattugiato',qt:'50g'},{nome:'Brodo vegetale',qt:'1L'}],
_dbEntry:{n:'Risotto ai funghi porcini (ricetta)',c:'Ricette',src:'RICETTE',k:380,p:11,gs:5,g:10,z:2,ch:60,fi:1.5,ca:110,fe:1.5,mg:30,k2:220,na:350,zn:1,fo:25,se:10,col:30}},

{id:'tpl_1024',nome:'Spaghetti alla carbonara',nome_en:'Spaghetti carbonara',categoria:'Primo piatto',porzioni:4,
note:'Rosolare guanciale a cubetti in padella senza olio fino a croccante. Sbattere tuorli con pecorino e pepe nero. Cuocere gli spaghetti al dente, scolare tenendo acqua di cottura. Mantecare fuori fuoco amalgamando uova e guanciale con poca acqua di cottura.',
note_en:'Brown diced guanciale in pan without oil until crispy. Beat egg yolks with pecorino and black pepper. Cook spaghetti al dente, drain keeping cooking water. Toss off heat combining eggs and guanciale with a little cooking water.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Guanciale',qt:'150g'},{nome:'Tuorli d uovo',qt:'6'},{nome:'Pecorino romano',qt:'80g'},{nome:'Pepe nero',qt:'q.b.'}],
_dbEntry:{n:'Spaghetti alla carbonara (ricetta)',c:'Ricette',src:'RICETTE',k:490,p:22,gs:8,g:20,z:1,ch:55,fi:1,ca:200,fe:2,mg:35,k2:250,na:700,zn:2.5,fo:60,se:20,col:320}},

{id:'tpl_1025',nome:'Lasagne al forno classiche',nome_en:'Classic baked lasagne',categoria:'Primo piatto',porzioni:6,
note:'Preparare ragu di carne con macinato, pomodoro e soffritto. Preparare besciamella. Alternare strati di pasta, ragu, besciamella e parmigiano in teglia. Cuocere in forno a 180 C per 45 minuti.',
note_en:'Prepare meat ragu with mince, tomato and soffritto. Make bechamel. Alternate layers of pasta, ragu, bechamel and parmesan in baking dish. Bake at 180 C for 45 minutes.',
ingredienti:[{nome:'Lasagne fresche',qt:'400g'},{nome:'Macinato misto',qt:'400g'},{nome:'Passata di pomodoro',qt:'400g'},{nome:'Latte intero',qt:'500ml'},{nome:'Farina',qt:'50g'},{nome:'Burro',qt:'50g'},{nome:'Parmigiano',qt:'80g'},{nome:'Cipolla',qt:'1'}],
_dbEntry:{n:'Lasagne al forno classiche (ricetta)',c:'Ricette',src:'RICETTE',k:380,p:22,gs:6,g:16,z:4,ch:38,fi:2,ca:220,fe:2.5,mg:35,k2:420,na:480,zn:3,fo:40,se:18,col:85}},

{id:'tpl_1026',nome:'Minestra di ceci e rosmarino',nome_en:'Chickpea and rosemary soup',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere aglio e rosmarino in olio. Aggiungere ceci lessati e brodo. Frullare meta della zuppa per darle cremosita. Aggiungere pasta corta o pasta mista. Cuocere al dente e servire con olio crudo.',
note_en:'Sauté garlic and rosemary in oil. Add cooked chickpeas and stock. Blend half the soup for creaminess. Add short pasta. Cook al dente and serve with raw oil.',
ingredienti:[{nome:'Ceci cotti',qt:'500g'},{nome:'Pasta corta',qt:'160g'},{nome:'Aglio',qt:'3 spicchi'},{nome:'Rosmarino',qt:'2 rametti'},{nome:'Olio extravergine',qt:'40ml'},{nome:'Brodo vegetale',qt:'800ml'},{nome:'Peperoncino',qt:'1'}],
_dbEntry:{n:'Minestra di ceci e rosmarino (ricetta)',c:'Ricette',src:'RICETTE',k:340,p:15,gs:1,g:8,z:2,ch:52,fi:11,ca:80,fe:4,mg:65,k2:600,na:280,zn:2,fo:140,se:5,col:0}},

{id:'tpl_1027',nome:'Risotto alla milanese',nome_en:'Milanese saffron risotto',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere cipolla in burro e midollo. Tostare il riso, sfumare con vino bianco. Aggiungere brodo caldo a mestoli. A meta cottura aggiungere lo zafferano sciolto in brodo caldo. Mantecare con burro freddo e parmigiano.',
note_en:'Sauté onion in butter and marrow. Toast rice, deglaze with white wine. Add hot stock in ladles. Halfway through add saffron dissolved in hot stock. Stir in cold butter and parmesan.',
ingredienti:[{nome:'Riso Carnaroli',qt:'320g'},{nome:'Zafferano',qt:'1 bustina'},{nome:'Cipolla bianca',qt:'1'},{nome:'Midollo di bue',qt:'30g'},{nome:'Burro',qt:'60g'},{nome:'Parmigiano',qt:'60g'},{nome:'Vino bianco',qt:'100ml'},{nome:'Brodo di carne',qt:'1L'}],
_dbEntry:{n:'Risotto alla milanese (ricetta)',c:'Ricette',src:'RICETTE',k:400,p:12,gs:7,g:14,z:2,ch:58,fi:0.5,ca:130,fe:1.5,mg:28,k2:200,na:400,zn:1.2,fo:20,se:8,col:45}},

{id:'tpl_1028',nome:'Pasta al pomodoro fresco',nome_en:'Pasta with fresh tomato',categoria:'Primo piatto',porzioni:4,
note:'Scottare i pomodori in acqua bollente, pelarli e tagliarli a pezzi. Soffriggere aglio in olio, aggiungere pomodori e cuocere 15 minuti. Cuocere la pasta al dente. Condire con il sugo e basilico fresco.',
note_en:'Blanch tomatoes in boiling water, peel and chop. Sauté garlic in oil, add tomatoes and cook 15 minutes. Cook pasta al dente. Dress with sauce and fresh basil.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Pomodori maturi',qt:'600g'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Basilico fresco',qt:'20g'},{nome:'Olio extravergine',qt:'40ml'},{nome:'Sale',qt:'q.b.'}],
_dbEntry:{n:'Pasta al pomodoro fresco (ricetta)',c:'Ricette',src:'RICETTE',k:350,p:11,gs:1,g:8,z:5,ch:60,fi:3,ca:40,fe:2,mg:38,k2:380,na:160,zn:0.9,fo:35,se:7,col:0}},

{id:'tpl_1029',nome:'Gnocchi al gorgonzola e noci',nome_en:'Gnocchi with gorgonzola and walnuts',categoria:'Primo piatto',porzioni:4,
note:'Sciogliere il gorgonzola a fuoco basso con panna e poco latte. Aggiustare di sale e pepe. Cuocere gli gnocchi in acqua salata finche vengono a galla. Scolare e condire con la crema di gorgonzola. Aggiungere gherigli di noce tritati.',
note_en:'Melt gorgonzola over low heat with cream and a little milk. Season with salt and pepper. Cook gnocchi in salted water until they float. Drain and dress with gorgonzola cream. Add chopped walnuts.',
ingredienti:[{nome:'Gnocchi di patate',qt:'600g'},{nome:'Gorgonzola dolce',qt:'150g'},{nome:'Panna da cucina',qt:'100ml'},{nome:'Gherigli di noce',qt:'50g'},{nome:'Latte',qt:'50ml'},{nome:'Pepe nero',qt:'q.b.'}],
_dbEntry:{n:'Gnocchi al gorgonzola e noci (ricetta)',c:'Ricette',src:'RICETTE',k:420,p:14,gs:9,g:18,z:2,ch:52,fi:2,ca:180,fe:1.5,mg:45,k2:280,na:520,zn:1.8,fo:25,se:6,col:55}},

{id:'tpl_1030',nome:'Penne all arrabbiata',nome_en:'Penne arrabbiata',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere aglio e peperoncino in abbondante olio. Aggiungere pomodori pelati spezzettati e cuocere 20 minuti. Cuocere le penne al dente. Scolare e saltare nel sugo. Aggiungere prezzemolo tritato.',
note_en:'Sauté garlic and chilli in plenty of oil. Add chopped peeled tomatoes and cook 20 minutes. Cook penne al dente. Drain and toss in sauce. Add chopped parsley.',
ingredienti:[{nome:'Penne rigate',qt:'320g'},{nome:'Pomodori pelati',qt:'400g'},{nome:'Aglio',qt:'3 spicchi'},{nome:'Peperoncino',qt:'2'},{nome:'Olio extravergine',qt:'50ml'},{nome:'Prezzemolo',qt:'15g'}],
_dbEntry:{n:'Penne all arrabbiata (ricetta)',c:'Ricette',src:'RICETTE',k:370,p:11,gs:1,g:10,z:4,ch:60,fi:3,ca:35,fe:2.2,mg:38,k2:380,na:200,zn:0.9,fo:30,se:7,col:0}},

{id:'tpl_1031',nome:'Ribollita toscana',nome_en:'Tuscan ribollita',categoria:'Primo piatto',porzioni:6,
note:'Soffriggere cipolla, carota, sedano. Aggiungere fagioli cannellini, cavolo nero, verza, pane raffermo e brodo. Cuocere 40 minuti. Aggiustare di sale. La ribollita si riscalda il giorno dopo con olio crudo.',
note_en:'Sauté onion, carrot, celery. Add cannellini beans, cavolo nero, savoy cabbage, stale bread and stock. Cook 40 minutes. Season with salt. Ribollita is reheated the next day with raw oil.',
ingredienti:[{nome:'Fagioli cannellini cotti',qt:'400g'},{nome:'Cavolo nero',qt:'300g'},{nome:'Verza',qt:'200g'},{nome:'Pane raffermo toscano',qt:'200g'},{nome:'Pomodori pelati',qt:'200g'},{nome:'Cipolla',qt:'1'},{nome:'Carota',qt:'2'},{nome:'Olio extravergine',qt:'50ml'},{nome:'Brodo vegetale',qt:'800ml'}],
_dbEntry:{n:'Ribollita toscana (ricetta)',c:'Ricette',src:'RICETTE',k:280,p:12,gs:1,g:7,z:4,ch:44,fi:10,ca:100,fe:3.5,mg:55,k2:550,na:360,zn:1.5,fo:110,se:4,col:0}},

{id:'tpl_1032',nome:'Pasta con le sarde',nome_en:'Pasta with sardines',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere cipolla con finocchietto selvatico. Aggiungere sarde fresche pulite, pinoli, uvetta e zafferano. Cuocere 10 minuti. Cuocere i bucatini al dente, condire con il sugo. Tostare pangrattato in olio e spolverare sul piatto.',
note_en:'Sauté onion with wild fennel. Add cleaned fresh sardines, pine nuts, raisins and saffron. Cook 10 minutes. Cook bucatini al dente, dress with sauce. Toast breadcrumbs in oil and sprinkle over dish.',
ingredienti:[{nome:'Bucatini',qt:'320g'},{nome:'Sarde fresche',qt:'300g'},{nome:'Finocchietto selvatico',qt:'100g'},{nome:'Cipolla',qt:'1'},{nome:'Pinoli',qt:'30g'},{nome:'Uvetta',qt:'30g'},{nome:'Zafferano',qt:'1 bustina'},{nome:'Pangrattato',qt:'40g'},{nome:'Olio extravergine',qt:'50ml'}],
_dbEntry:{n:'Pasta con le sarde (ricetta)',c:'Ricette',src:'RICETTE',k:420,p:20,gs:2,g:12,z:5,ch:58,fi:3,ca:120,fe:2.5,mg:50,k2:380,na:280,zn:1.5,fo:45,se:30,col:45}},

{id:'tpl_1033',nome:'Risotto al radicchio e speck',nome_en:'Risotto with radicchio and speck',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere scalogno in burro. Aggiungere speck a cubetti e rosolare. Aggiungere radicchio tagliato e far appassire. Tostare il riso e sfumare con vino rosso. Aggiungere brodo caldo. Mantecare con burro e parmigiano.',
note_en:'Sauté shallot in butter. Add diced speck and brown. Add sliced radicchio and wilt. Toast rice and deglaze with red wine. Add hot stock. Stir in butter and parmesan.',
ingredienti:[{nome:'Riso Vialone Nano',qt:'320g'},{nome:'Radicchio',qt:'200g'},{nome:'Speck',qt:'100g'},{nome:'Scalogno',qt:'2'},{nome:'Vino rosso',qt:'100ml'},{nome:'Burro',qt:'40g'},{nome:'Parmigiano',qt:'50g'},{nome:'Brodo vegetale',qt:'1L'}],
_dbEntry:{n:'Risotto al radicchio e speck (ricetta)',c:'Ricette',src:'RICETTE',k:390,p:15,gs:5,g:11,z:3,ch:58,fi:1.5,ca:100,fe:2,mg:28,k2:280,na:650,zn:1.5,fo:30,se:12,col:35}},

{id:'tpl_1034',nome:'Zuppa di lenticchie rosse',nome_en:'Red lentil soup',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere cipolla, aglio e curcuma in olio. Aggiungere lenticchie rosse lavate e brodo. Cuocere 25 minuti. Frullare fino a crema liscia. Aggiustare di sale e pepe. Servire con pane tostato e olio al rosmarino.',
note_en:'Sauté onion, garlic and turmeric in oil. Add washed red lentils and stock. Cook 25 minutes. Blend to smooth cream. Season with salt and pepper. Serve with toasted bread and rosemary oil.',
ingredienti:[{nome:'Lenticchie rosse',qt:'300g'},{nome:'Cipolla',qt:'1'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Curcuma',qt:'1 cucchiaino'},{nome:'Cumino',qt:'1 cucchiaino'},{nome:'Brodo vegetale',qt:'1L'},{nome:'Olio extravergine',qt:'30ml'}],
_dbEntry:{n:'Zuppa di lenticchie rosse (ricetta)',c:'Ricette',src:'RICETTE',k:290,p:17,gs:0.8,g:5,z:3,ch:48,fi:10,ca:55,fe:4,mg:65,k2:620,na:350,zn:2,fo:160,se:6,col:0}},

{id:'tpl_1035',nome:'Pasta con broccoli e acciughe',nome_en:'Pasta with broccoli and anchovies',categoria:'Primo piatto',porzioni:4,
note:'Lessare i broccoli in acqua salata, tenere lacqua di cottura per la pasta. Soffriggere aglio, acciughe e peperoncino in olio fino a sciogliere le acciughe. Cuocere la pasta nell acqua dei broccoli. Saltare tutto insieme.',
note_en:'Boil broccoli in salted water, keep cooking water for pasta. Sauté garlic, anchovies and chilli in oil until anchovies dissolve. Cook pasta in broccoli water. Toss everything together.',
ingredienti:[{nome:'Orecchiette',qt:'320g'},{nome:'Broccoli',qt:'400g'},{nome:'Acciughe sott olio',qt:'6'},{nome:'Aglio',qt:'3 spicchi'},{nome:'Peperoncino',qt:'1'},{nome:'Olio extravergine',qt:'50ml'}],
_dbEntry:{n:'Pasta con broccoli e acciughe (ricetta)',c:'Ricette',src:'RICETTE',k:370,p:15,gs:1.5,g:10,z:3,ch:55,fi:5,ca:80,fe:2.5,mg:55,k2:450,na:380,zn:1.5,fo:90,se:12,col:12}},

{id:'tpl_1036',nome:'Risi e bisi veneti',nome_en:'Venetian rice and peas',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere cipolla e pancetta in burro. Aggiungere piselli freschi e brodo. Aggiungere il riso e cuocere aggiungendo brodo. Il piatto deve risultare piu morbido di un risotto. Mantecare con burro e parmigiano.',
note_en:'Sauté onion and pancetta in butter. Add fresh peas and stock. Add rice and cook adding stock. Dish should be softer than a risotto. Stir in butter and parmesan.',
ingredienti:[{nome:'Riso Vialone Nano',qt:'280g'},{nome:'Piselli freschi',qt:'400g'},{nome:'Pancetta',qt:'80g'},{nome:'Cipolla',qt:'1'},{nome:'Burro',qt:'40g'},{nome:'Parmigiano',qt:'50g'},{nome:'Brodo vegetale',qt:'1.2L'}],
_dbEntry:{n:'Risi e bisi veneti (ricetta)',c:'Ricette',src:'RICETTE',k:370,p:14,gs:4,g:10,z:5,ch:54,fi:5,ca:100,fe:2,mg:40,k2:350,na:420,zn:1.2,fo:60,se:8,col:35}},

{id:'tpl_1037',nome:'Pasta alla norma',nome_en:'Pasta alla Norma',categoria:'Primo piatto',porzioni:4,
note:'Friggere melanzane a cubetti in olio abbondante, scolare su carta. Preparare sugo di pomodoro con aglio e basilico. Cuocere la pasta al dente. Condire con sugo, melanzane fritte e ricotta salata grattugiata.',
note_en:'Fry diced aubergine in plenty of oil, drain on paper. Prepare tomato sauce with garlic and basil. Cook pasta al dente. Dress with sauce, fried aubergine and grated salted ricotta.',
ingredienti:[{nome:'Rigatoni',qt:'320g'},{nome:'Melanzane',qt:'400g'},{nome:'Pomodori pelati',qt:'400g'},{nome:'Ricotta salata',qt:'80g'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Basilico',qt:'15g'},{nome:'Olio per friggere',qt:'200ml'}],
_dbEntry:{n:'Pasta alla norma (ricetta)',c:'Ricette',src:'RICETTE',k:430,p:13,gs:2,g:14,z:5,ch:62,fi:4,ca:100,fe:2,mg:38,k2:400,na:280,zn:1,fo:40,se:8,col:10}},

{id:'tpl_1038',nome:'Zuppa di farro e verdure',nome_en:'Farro and vegetable soup',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere cipolla, carota, sedano e aglio. Aggiungere farro perlato, pomodori a cubetti e brodo vegetale. Cuocere 40 minuti. Aggiungere erbe aromatiche. Servire con olio extravergine a crudo.',
note_en:'Sauté onion, carrot, celery and garlic. Add pearled farro, diced tomatoes and vegetable stock. Cook 40 minutes. Add aromatic herbs. Serve with raw extra virgin olive oil.',
ingredienti:[{nome:'Farro perlato',qt:'250g'},{nome:'Carota',qt:'2'},{nome:'Sedano',qt:'2 coste'},{nome:'Cipolla',qt:'1'},{nome:'Pomodori a pezzetti',qt:'200g'},{nome:'Brodo vegetale',qt:'1.2L'},{nome:'Olio extravergine',qt:'30ml'},{nome:'Erbe miste',qt:'q.b.'}],
_dbEntry:{n:'Zuppa di farro e verdure (ricetta)',c:'Ricette',src:'RICETTE',k:270,p:10,gs:0.5,g:5,z:4,ch:48,fi:7,ca:50,fe:2.5,mg:55,k2:450,na:320,zn:1.5,fo:55,se:6,col:0}},

{id:'tpl_1039',nome:'Pasta e patate alla napoletana',nome_en:'Neapolitan pasta and potatoes',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere cipolla, aglio e rosmarino. Aggiungere patate a cubetti e pomodori. Versare brodo e cuocere 20 minuti. Aggiungere pasta mista e finire la cottura. Il piatto deve essere cremoso. Finire con pecorino e olio.',
note_en:'Sauté onion, garlic and rosemary. Add diced potatoes and tomatoes. Pour in stock and cook 20 minutes. Add mixed pasta and finish cooking. Dish should be creamy. Finish with pecorino and oil.',
ingredienti:[{nome:'Pasta mista',qt:'200g'},{nome:'Patate',qt:'400g'},{nome:'Pomodori pelati',qt:'200g'},{nome:'Cipolla',qt:'1'},{nome:'Rosmarino',qt:'1 rametto'},{nome:'Pecorino',qt:'40g'},{nome:'Olio extravergine',qt:'40ml'},{nome:'Brodo vegetale',qt:'800ml'}],
_dbEntry:{n:'Pasta e patate alla napoletana (ricetta)',c:'Ricette',src:'RICETTE',k:340,p:10,gs:1.5,g:7,z:3,ch:58,fi:4,ca:80,fe:2,mg:40,k2:700,na:380,zn:1,fo:35,se:5,col:8}},

{id:'tpl_1040',nome:'Risotto al limone e gamberi',nome_en:'Lemon and prawn risotto',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere scalogno in olio. Aggiungere gamberi sgusciati, rosolare e togliere. Tostare il riso, sfumare con prosecco. Aggiungere brodo di pesce. A cottura quasi ultimata rimettere i gamberi. Mantecare con olio e scorza di limone.',
note_en:'Sauté shallot in oil. Add peeled prawns, brown and remove. Toast rice, deglaze with prosecco. Add fish stock. Near end of cooking return prawns. Stir in oil and lemon zest.',
ingredienti:[{nome:'Riso Carnaroli',qt:'320g'},{nome:'Gamberi',qt:'300g'},{nome:'Scalogno',qt:'2'},{nome:'Limone',qt:'2'},{nome:'Prosecco',qt:'100ml'},{nome:'Olio extravergine',qt:'40ml'},{nome:'Brodo di pesce',qt:'1L'},{nome:'Prezzemolo',qt:'15g'}],
_dbEntry:{n:'Risotto al limone e gamberi (ricetta)',c:'Ricette',src:'RICETTE',k:370,p:18,gs:1.5,g:8,z:2,ch:54,fi:0.5,ca:80,fe:2,mg:45,k2:380,na:380,zn:2,fo:35,se:25,col:120}},

{id:'tpl_1041',nome:'Strozzapreti al ragu di salsiccia',nome_en:'Strozzapreti with sausage ragu',categoria:'Primo piatto',porzioni:4,
note:'Rosolare la salsiccia sbriciolata con cipolla e aglio. Sfumare con vino rosso. Aggiungere pomodoro e cuocere 30 minuti. Cuocere gli strozzapreti al dente. Condire con il ragu e pecorino grattugiato.',
note_en:'Brown crumbled sausage with onion and garlic. Deglaze with red wine. Add tomato and cook 30 minutes. Cook strozzapreti al dente. Dress with ragu and grated pecorino.',
ingredienti:[{nome:'Strozzapreti',qt:'320g'},{nome:'Salsiccia',qt:'250g'},{nome:'Pomodori pelati',qt:'300g'},{nome:'Cipolla',qt:'1'},{nome:'Vino rosso',qt:'100ml'},{nome:'Pecorino',qt:'40g'},{nome:'Olio extravergine',qt:'30ml'}],
_dbEntry:{n:'Strozzapreti al ragu di salsiccia (ricetta)',c:'Ricette',src:'RICETTE',k:450,p:20,gs:5,g:15,z:4,ch:56,fi:2.5,ca:90,fe:2.5,mg:35,k2:380,na:580,zn:2.5,fo:30,se:15,col:55}},

{id:'tpl_1042',nome:'Pasta al tonno e capperi',nome_en:'Pasta with tuna and capers',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere aglio in olio, aggiungere tonno sgocciolato sbriciolato. Aggiungere capperi, olive, pomodorini. Cuocere 10 minuti. Cuocere la pasta al dente. Condire con il sugo e prezzemolo fresco.',
note_en:'Sauté garlic in oil, add drained crumbled tuna. Add capers, olives, cherry tomatoes. Cook 10 minutes. Cook pasta al dente. Dress with sauce and fresh parsley.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Tonno sott olio',qt:'200g'},{nome:'Capperi',qt:'30g'},{nome:'Olive nere',qt:'60g'},{nome:'Pomodorini',qt:'200g'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Olio extravergine',qt:'40ml'}],
_dbEntry:{n:'Pasta al tonno e capperi (ricetta)',c:'Ricette',src:'RICETTE',k:390,p:22,gs:2,g:10,z:3,ch:54,fi:2.5,ca:50,fe:2,mg:45,k2:450,na:680,zn:1.5,fo:35,se:35,col:30}},

{id:'tpl_1043',nome:'Pasta alla gricia',nome_en:'Pasta alla gricia',categoria:'Primo piatto',porzioni:4,
note:'Rosolare il guanciale tagliato a listelli in padella senza olio fino a croccante. Cuocere i rigatoni al dente, scolare tenendo acqua di cottura. Mantecare in padella con guanciale, pecorino grattugiato e pepe nero. Aggiungere acqua di cottura per ottenere una crema.',
note_en:'Brown guanciale strips in pan without oil until crispy. Cook rigatoni al dente, drain keeping cooking water. Toss in pan with guanciale, grated pecorino and black pepper. Add cooking water to achieve a cream.',
ingredienti:[{nome:'Rigatoni',qt:'320g'},{nome:'Guanciale',qt:'150g'},{nome:'Pecorino romano',qt:'80g'},{nome:'Pepe nero',qt:'q.b.'}],
_dbEntry:{n:'Pasta alla gricia (ricetta)',c:'Ricette',src:'RICETTE',k:460,p:19,gs:7,g:16,z:1,ch:58,fi:1,ca:170,fe:1.5,mg:30,k2:220,na:700,zn:2,fo:20,se:15,col:55}},

{id:'tpl_1044',nome:'Zuppa di cipolle gratinata',nome_en:'Gratineed onion soup',categoria:'Primo piatto',porzioni:4,
note:'Affettare cipolle e cuocere lentamente in burro per 40 minuti fino a caramellare. Sfumare con vino bianco. Aggiungere brodo di carne. Versare in ciotole da forno, coprire con pane tostato e formaggio groviera. Gratinare in forno a 200 C.',
note_en:'Slice onions and cook slowly in butter for 40 minutes until caramelised. Deglaze with white wine. Add beef stock. Pour into oven bowls, cover with toasted bread and gruyere. Gratinee in oven at 200 C.',
ingredienti:[{nome:'Cipolle',qt:'800g'},{nome:'Brodo di carne',qt:'800ml'},{nome:'Burro',qt:'50g'},{nome:'Vino bianco',qt:'100ml'},{nome:'Pane raffermo',qt:'100g'},{nome:'Groviera',qt:'100g'}],
_dbEntry:{n:'Zuppa di cipolle gratinata (ricetta)',c:'Ricette',src:'RICETTE',k:300,p:12,gs:5,g:12,z:10,ch:35,fi:3,ca:250,fe:1,mg:30,k2:280,na:650,zn:1.5,fo:30,se:6,col:40}},

{id:'tpl_1045',nome:'Risotto agli asparagi',nome_en:'Asparagus risotto',categoria:'Primo piatto',porzioni:4,
note:'Cuocere gli asparagi, tenere le punte e frullare i gambi con poco brodo. Soffriggere scalogno, tostare riso e sfumare con vino bianco. Aggiungere brodo e la crema di asparagi. A meta cottura aggiungere le punte. Mantecare con burro e parmigiano.',
note_en:'Cook asparagus, keep tips and blend stalks with a little stock. Sauté shallot, toast rice and deglaze with white wine. Add stock and asparagus cream. Halfway add tips. Stir in butter and parmesan.',
ingredienti:[{nome:'Riso Carnaroli',qt:'320g'},{nome:'Asparagi',qt:'500g'},{nome:'Scalogno',qt:'2'},{nome:'Burro',qt:'40g'},{nome:'Parmigiano',qt:'50g'},{nome:'Vino bianco',qt:'100ml'},{nome:'Brodo vegetale',qt:'1L'}],
_dbEntry:{n:'Risotto agli asparagi (ricetta)',c:'Ricette',src:'RICETTE',k:370,p:12,gs:4,g:9,z:3,ch:59,fi:2.5,ca:90,fe:2,mg:30,k2:300,na:350,zn:1,fo:80,se:5,col:25}},

{id:'tpl_1046',nome:'Pasta con zucchine e fiori',nome_en:'Pasta with courgettes and flowers',categoria:'Primo piatto',porzioni:4,
note:'Affettare le zucchine e saltare in olio con aglio. Aggiungere i fiori di zucca puliti. Cuocere la pasta al dente. Amalgamare con le zucchine, aggiungere pecorino e menta fresca.',
note_en:'Slice courgettes and sauté in oil with garlic. Add cleaned courgette flowers. Cook pasta al dente. Combine with courgettes, add pecorino and fresh mint.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Zucchine',qt:'400g'},{nome:'Fiori di zucca',qt:'8'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Pecorino',qt:'50g'},{nome:'Menta fresca',qt:'10g'},{nome:'Olio extravergine',qt:'40ml'}],
_dbEntry:{n:'Pasta con zucchine e fiori (ricetta)',c:'Ricette',src:'RICETTE',k:360,p:13,gs:2,g:9,z:4,ch:56,fi:3,ca:120,fe:2,mg:42,k2:380,na:240,zn:1.2,fo:50,se:8,col:10}},

{id:'tpl_1047',nome:'Minestrone alla genovese',nome_en:'Genoese minestrone',categoria:'Primo piatto',porzioni:6,
note:'Soffriggere le verdure a cubetti. Aggiungere fagioli, patate e brodo. Cuocere 30 minuti. Aggiungere pasta corta e cuocere al dente. Condire con un cucchiaio di pesto genovese. Servire tiepido.',
note_en:'Sauté diced vegetables. Add beans, potatoes and stock. Cook 30 minutes. Add short pasta and cook al dente. Dress with a spoonful of Genoese pesto. Serve warm.',
ingredienti:[{nome:'Verdure miste stagionali',qt:'600g'},{nome:'Fagioli borlotti cotti',qt:'250g'},{nome:'Patate',qt:'200g'},{nome:'Pasta corta',qt:'100g'},{nome:'Pesto genovese',qt:'80g'},{nome:'Brodo vegetale',qt:'1.5L'}],
_dbEntry:{n:'Minestrone alla genovese (ricetta)',c:'Ricette',src:'RICETTE',k:280,p:11,gs:1,g:8,z:5,ch:42,fi:8,ca:80,fe:2.5,mg:50,k2:500,na:380,zn:1.2,fo:90,se:5,col:3}},

{id:'tpl_1048',nome:'Pasta al forno siciliana',nome_en:'Sicilian baked pasta',categoria:'Primo piatto',porzioni:6,
note:'Cuocere pasta al dente. Preparare sugo di carne con macinato e pomodoro. In teglia alternare pasta, sugo, piselli, uova sode affettate e caciocavallo. Chiudere con sugo e formaggio. Cuocere in forno a 180 C per 30 minuti.',
note_en:'Cook pasta al dente. Prepare meat sauce with mince and tomato. In baking dish alternate pasta, sauce, peas, sliced hard-boiled eggs and caciocavallo. Top with sauce and cheese. Bake at 180 C for 30 minutes.',
ingredienti:[{nome:'Rigatoni',qt:'400g'},{nome:'Macinato di manzo',qt:'300g'},{nome:'Pomodori pelati',qt:'400g'},{nome:'Piselli',qt:'100g'},{nome:'Uova sode',qt:'3'},{nome:'Caciocavallo',qt:'150g'},{nome:'Cipolla',qt:'1'}],
_dbEntry:{n:'Pasta al forno siciliana (ricetta)',c:'Ricette',src:'RICETTE',k:420,p:22,gs:5,g:14,z:4,ch:52,fi:3,ca:180,fe:3,mg:38,k2:380,na:480,zn:3,fo:45,se:18,col:140}},

{id:'tpl_1049',nome:'Spaghetti alle vongole in bianco',nome_en:'Spaghetti with clams in white sauce',categoria:'Primo piatto',porzioni:4,
note:'Far aprire le vongole in padella coperta con aglio e vino bianco. Filtrare il liquido. Soffriggere aglio e prezzemolo. Aggiungere il liquido delle vongole. Cuocere gli spaghetti al dente. Saltare in padella con le vongole e il loro liquido.',
note_en:'Open clams in covered pan with garlic and white wine. Filter liquid. Sauté garlic and parsley. Add clam liquid. Cook spaghetti al dente. Toss in pan with clams and their liquid.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Vongole',qt:'800g'},{nome:'Aglio',qt:'3 spicchi'},{nome:'Vino bianco',qt:'150ml'},{nome:'Prezzemolo',qt:'20g'},{nome:'Olio extravergine',qt:'50ml'},{nome:'Peperoncino',qt:'1'}],
_dbEntry:{n:'Spaghetti alle vongole in bianco (ricetta)',c:'Ricette',src:'RICETTE',k:360,p:18,gs:1.5,g:10,z:2,ch:52,fi:1,ca:80,fe:3.5,mg:45,k2:380,na:380,zn:2,fo:30,se:22,col:35}},

{id:'tpl_1050',nome:'Risotto al nero di seppia',nome_en:'Black squid ink risotto',categoria:'Primo piatto',porzioni:4,
note:'Pulire le seppie tenendo il sacchetto del nero. Rosolare cipolla e aglio in olio. Aggiungere le seppie a pezzi e sfumare con vino bianco. Tostare il riso nella base. Aggiungere brodo di pesce e il nero di seppia. Mantecare con olio crudo.',
note_en:'Clean squid keeping ink sac. Brown onion and garlic in oil. Add squid pieces and deglaze with white wine. Toast rice in base. Add fish stock and squid ink. Stir in raw oil.',
ingredienti:[{nome:'Riso Carnaroli',qt:'320g'},{nome:'Seppie',qt:'400g'},{nome:'Nero di seppia',qt:'2 bustine'},{nome:'Cipolla',qt:'1'},{nome:'Vino bianco',qt:'120ml'},{nome:'Olio extravergine',qt:'50ml'},{nome:'Brodo di pesce',qt:'1L'}],
_dbEntry:{n:'Risotto al nero di seppia (ricetta)',c:'Ricette',src:'RICETTE',k:370,p:20,gs:1.5,g:9,z:2,ch:52,fi:0.5,ca:50,fe:2.5,mg:50,k2:420,na:380,zn:2,fo:25,se:30,col:80}},

{id:'tpl_1051',nome:'Pasta al pistacchio di Bronte',nome_en:'Pasta with Bronte pistachio',categoria:'Primo piatto',porzioni:4,
note:'Frullare pistacchi con aglio, olio e poca acqua per creare il pesto. Rosolare la salsiccia sbriciolata. Cuocere i rigatoni al dente. Mantecare con pesto di pistacchio, salsiccia e un mestolo di acqua di cottura.',
note_en:'Blend pistachios with garlic, oil and a little water to make pesto. Brown crumbled sausage. Cook rigatoni al dente. Toss with pistachio pesto, sausage and a ladle of cooking water.',
ingredienti:[{nome:'Rigatoni',qt:'320g'},{nome:'Pistacchi di Bronte',qt:'100g'},{nome:'Salsiccia',qt:'200g'},{nome:'Aglio',qt:'1 spicchio'},{nome:'Olio extravergine',qt:'50ml'},{nome:'Parmigiano',qt:'30g'}],
_dbEntry:{n:'Pasta al pistacchio di Bronte (ricetta)',c:'Ricette',src:'RICETTE',k:490,p:20,gs:4,g:22,z:3,ch:55,fi:3,ca:80,fe:2.5,mg:55,k2:520,na:480,zn:2,fo:35,se:10,col:40}},

{id:'tpl_1052',nome:'Minestra di orzo e verdure',nome_en:'Barley and vegetable soup',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere le verdure a cubetti. Aggiungere orzo perlato, pomodori e brodo. Cuocere 40 minuti mescolando spesso. Condire con olio extravergine e prezzemolo. Servire caldo con parmigiano a parte.',
note_en:'Sauté diced vegetables. Add pearled barley, tomatoes and stock. Cook 40 minutes stirring often. Season with extra virgin olive oil and parsley. Serve hot with parmesan on the side.',
ingredienti:[{nome:'Orzo perlato',qt:'250g'},{nome:'Carote',qt:'2'},{nome:'Sedano',qt:'2 coste'},{nome:'Cipolla',qt:'1'},{nome:'Pomodori',qt:'200g'},{nome:'Brodo vegetale',qt:'1.2L'},{nome:'Olio extravergine',qt:'30ml'}],
_dbEntry:{n:'Minestra di orzo e verdure (ricetta)',c:'Ricette',src:'RICETTE',k:280,p:9,gs:0.5,g:5,z:4,ch:50,fi:7,ca:45,fe:2.5,mg:45,k2:420,na:310,zn:1.5,fo:35,se:8,col:0}},

{id:'tpl_1053',nome:'Caserecce al pesto di rucola',nome_en:'Caserecce with rocket pesto',categoria:'Primo piatto',porzioni:4,
note:'Frullare rucola, pinoli, aglio, parmigiano e olio per il pesto. Cuocere le caserecce al dente. Scolare tenendo acqua di cottura. Mantecare con il pesto di rucola, aggiungendo acqua di cottura per ammorbidire. Guarnire con scaglie di parmigiano.',
note_en:'Blend rocket, pine nuts, garlic, parmesan and oil for pesto. Cook caserecce al dente. Drain keeping cooking water. Toss with rocket pesto, adding cooking water to soften. Garnish with parmesan shavings.',
ingredienti:[{nome:'Caserecce',qt:'320g'},{nome:'Rucola',qt:'80g'},{nome:'Pinoli',qt:'30g'},{nome:'Parmigiano',qt:'50g'},{nome:'Aglio',qt:'1 spicchio'},{nome:'Olio extravergine',qt:'80ml'}],
_dbEntry:{n:'Caserecce al pesto di rucola (ricetta)',c:'Ricette',src:'RICETTE',k:430,p:14,gs:3,g:17,z:2,ch:58,fi:2,ca:120,fe:2,mg:38,k2:250,na:200,zn:1.2,fo:50,se:8,col:8}},

{id:'tpl_1054',nome:'Riso pilaf con verdure',nome_en:'Vegetable pilaf rice',categoria:'Primo piatto',porzioni:4,
note:'Tostare il riso Basmati in burro con cipolla. Aggiungere brodo bollente in quantita doppia rispetto al riso. Chiudere il coperchio e cuocere a fuoco bassissimo 18 minuti senza mai aprire. Sgranare con una forchetta e aggiungere verdure saltate.',
note_en:'Toast Basmati rice in butter with onion. Add boiling stock in double the amount of rice. Cover and cook on very low heat 18 minutes without opening. Fluff with fork and add sautéed vegetables.',
ingredienti:[{nome:'Riso Basmati',qt:'300g'},{nome:'Cipolla',qt:'1'},{nome:'Burro',qt:'30g'},{nome:'Verdure miste',qt:'250g'},{nome:'Brodo vegetale',qt:'600ml'},{nome:'Spezie aromatiche',qt:'q.b.'}],
_dbEntry:{n:'Riso pilaf con verdure (ricetta)',c:'Ricette',src:'RICETTE',k:320,p:7,gs:2,g:6,z:4,ch:58,fi:3,ca:45,fe:1.5,mg:35,k2:280,na:280,zn:0.8,fo:30,se:5,col:10}},

{id:'tpl_1055',nome:'Pasta con peperoni arrostiti',nome_en:'Pasta with roasted peppers',categoria:'Primo piatto',porzioni:4,
note:'Arrostire i peperoni in forno o sul gas, pelarli e tagliarli a listarelle. Soffriggere aglio in olio, aggiungere i peperoni, acciughe e capperi. Cuocere la pasta al dente. Saltare tutto insieme con prezzemolo.',
note_en:'Roast peppers in oven or on gas, peel and slice. Sauté garlic in oil, add peppers, anchovies and capers. Cook pasta al dente. Toss everything together with parsley.',
ingredienti:[{nome:'Fusilli',qt:'320g'},{nome:'Peperoni rossi',qt:'4'},{nome:'Acciughe',qt:'4'},{nome:'Capperi',qt:'20g'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Olio extravergine',qt:'40ml'},{nome:'Prezzemolo',qt:'15g'}],
_dbEntry:{n:'Pasta con peperoni arrostiti (ricetta)',c:'Ricette',src:'RICETTE',k:370,p:12,gs:1.5,g:9,z:6,ch:60,fi:3,ca:50,fe:2.5,mg:45,k2:420,na:420,zn:1,fo:55,se:10,col:8}},

{id:'tpl_1056',nome:'Zuppa di pane toscana',nome_en:'Tuscan bread soup',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere aglio in olio, aggiungere pomodori maturi spezzettati. Aggiungere pane toscano raffermo spezzettato e brodo vegetale. Cuocere mescolando finche il pane si ammorbidisce. Aggiustare di sale e pepe. Servire con olio crudo.',
note_en:'Sauté garlic in oil, add roughly chopped ripe tomatoes. Add crumbled stale Tuscan bread and vegetable stock. Cook stirring until bread softens. Season with salt and pepper. Serve with raw oil.',
ingredienti:[{nome:'Pane toscano raffermo',qt:'300g'},{nome:'Pomodori maturi',qt:'500g'},{nome:'Aglio',qt:'3 spicchi'},{nome:'Olio extravergine',qt:'60ml'},{nome:'Brodo vegetale',qt:'600ml'},{nome:'Basilico',qt:'15g'}],
_dbEntry:{n:'Zuppa di pane toscana (ricetta)',c:'Ricette',src:'RICETTE',k:290,p:7,gs:1,g:10,z:5,ch:44,fi:4,ca:55,fe:2,mg:30,k2:350,na:440,zn:0.8,fo:30,se:5,col:0}},

{id:'tpl_1057',nome:'Pasta alla sorrentina',nome_en:'Pasta alla sorrentina',categoria:'Primo piatto',porzioni:4,
note:'Preparare sugo di pomodoro fresco con basilico. Cuocere i rigatoni al dente. In teglia alternare pasta, sugo, mozzarella a cubetti e parmigiano. Cuocere in forno a 200 C per 15 minuti finche la mozzarella fila.',
note_en:'Make fresh tomato sauce with basil. Cook rigatoni al dente. In baking dish alternate pasta, sauce, diced mozzarella and parmesan. Bake at 200 C for 15 minutes until mozzarella melts and stretches.',
ingredienti:[{nome:'Rigatoni',qt:'320g'},{nome:'Pomodori maturi',qt:'500g'},{nome:'Mozzarella',qt:'200g'},{nome:'Parmigiano',qt:'50g'},{nome:'Basilico',qt:'15g'},{nome:'Olio extravergine',qt:'30ml'}],
_dbEntry:{n:'Pasta alla sorrentina (ricetta)',c:'Ricette',src:'RICETTE',k:420,p:18,gs:5,g:14,z:5,ch:56,fi:2.5,ca:250,fe:1.5,mg:38,k2:350,na:380,zn:2,fo:35,se:12,col:40}},

{id:'tpl_1058',nome:'Pasta con la mollica di pane',nome_en:'Pasta with toasted breadcrumbs',categoria:'Primo piatto',porzioni:4,
note:'Tostare la mollica di pane in olio con aglio e acciughe fino a doratura. Condire con peperoncino. Cuocere la pasta al dente. Scolare e condire con la mollica tostata, aglio e prezzemolo.',
note_en:'Toast breadcrumbs in oil with garlic and anchovies until golden. Season with chilli. Cook pasta al dente. Drain and dress with toasted crumbs, garlic and parsley.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Mollica di pane',qt:'80g'},{nome:'Acciughe',qt:'4'},{nome:'Aglio',qt:'3 spicchi'},{nome:'Peperoncino',qt:'1'},{nome:'Olio extravergine',qt:'60ml'},{nome:'Prezzemolo',qt:'15g'}],
_dbEntry:{n:'Pasta con la mollica di pane (ricetta)',c:'Ricette',src:'RICETTE',k:400,p:12,gs:1.5,g:12,z:2,ch:60,fi:2,ca:45,fe:2.5,mg:35,k2:230,na:420,zn:0.9,fo:25,se:8,col:5}},

{id:'tpl_1059',nome:'Risotto zucca e amaretti',nome_en:'Pumpkin and amaretti risotto',categoria:'Primo piatto',porzioni:4,
note:'Arrostire la zucca in forno. Soffriggere scalogno in burro, tostare il riso, sfumare con vino bianco. Aggiungere brodo e la polpa di zucca schiacciata. Mantecare con burro e parmigiano. Servire con amaretti sbriciolati.',
note_en:'Roast pumpkin in oven. Sauté shallot in butter, toast rice, deglaze with white wine. Add stock and mashed pumpkin flesh. Stir in butter and parmesan. Serve with crumbled amaretti.',
ingredienti:[{nome:'Riso Carnaroli',qt:'320g'},{nome:'Zucca',qt:'400g'},{nome:'Scalogno',qt:'2'},{nome:'Burro',qt:'50g'},{nome:'Parmigiano',qt:'50g'},{nome:'Amaretti',qt:'30g'},{nome:'Vino bianco',qt:'100ml'},{nome:'Brodo vegetale',qt:'1L'}],
_dbEntry:{n:'Risotto zucca e amaretti (ricetta)',c:'Ricette',src:'RICETTE',k:390,p:11,gs:5,g:11,z:8,ch:62,fi:2,ca:100,fe:1.5,mg:30,k2:380,na:350,zn:1,fo:28,se:6,col:30}},

{id:'tpl_1060',nome:'Pasta con ragù alla bolognese',nome_en:'Pasta with Bolognese ragu',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere cipolla, carota, sedano. Aggiungere macinato misto e rosolare. Sfumare con vino rosso. Aggiungere pomodori e latte. Cuocere a fuoco lento almeno 2 ore. Servire con tagliatelle al uovo e parmigiano.',
note_en:'Sauté onion, carrot, celery. Add mixed mince and brown. Deglaze with red wine. Add tomatoes and milk. Cook on low heat at least 2 hours. Serve with egg tagliatelle and parmesan.',
ingredienti:[{nome:'Tagliatelle all uovo',qt:'320g'},{nome:'Macinato misto',qt:'400g'},{nome:'Pomodori pelati',qt:'300g'},{nome:'Cipolla',qt:'1'},{nome:'Carota',qt:'1'},{nome:'Sedano',qt:'1 costa'},{nome:'Vino rosso',qt:'100ml'},{nome:'Latte',qt:'50ml'},{nome:'Parmigiano',qt:'50g'}],
_dbEntry:{n:'Pasta con ragu alla bolognese (ricetta)',c:'Ricette',src:'RICETTE',k:450,p:25,gs:5,g:14,z:4,ch:52,fi:2.5,ca:120,fe:3,mg:40,k2:480,na:420,zn:3.5,fo:50,se:18,col:75}},

{id:'tpl_1061',nome:'Minestrone di primavera',nome_en:'Spring minestrone',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere cipolla e aglio. Aggiungere carote, piselli, asparagi a pezzetti, spinaci e brodo. Cuocere 20 minuti. Aggiungere pasta corta o pastina. Servire con parmigiano e olio extravergine a crudo.',
note_en:'Sauté onion and garlic. Add carrots, peas, chopped asparagus, spinach and stock. Cook 20 minutes. Add short pasta or pastina. Serve with parmesan and raw extra virgin olive oil.',
ingredienti:[{nome:'Pastina',qt:'120g'},{nome:'Piselli',qt:'150g'},{nome:'Asparagi',qt:'200g'},{nome:'Carote',qt:'2'},{nome:'Spinaci freschi',qt:'150g'},{nome:'Cipolla',qt:'1'},{nome:'Brodo vegetale',qt:'1.2L'},{nome:'Parmigiano',qt:'40g'}],
_dbEntry:{n:'Minestrone di primavera (ricetta)',c:'Ricette',src:'RICETTE',k:260,p:10,gs:0.5,g:4,z:5,ch:46,fi:7,ca:80,fe:2.5,mg:48,k2:480,na:330,zn:1.2,fo:100,se:5,col:5}},

{id:'tpl_1062',nome:'Pasta alla puttanesca',nome_en:'Pasta puttanesca',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere aglio in olio, aggiungere acciughe fino a scioglierle. Aggiungere olive nere, capperi e pomodori. Cuocere 20 minuti. Cuocere gli spaghetti al dente e saltarli nel sugo. Finire con prezzemolo.',
note_en:'Sauté garlic in oil, add anchovies until dissolved. Add black olives, capers and tomatoes. Cook 20 minutes. Cook spaghetti al dente and toss in sauce. Finish with parsley.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Pomodori pelati',qt:'400g'},{nome:'Olive nere',qt:'80g'},{nome:'Capperi',qt:'30g'},{nome:'Acciughe',qt:'6'},{nome:'Aglio',qt:'3 spicchi'},{nome:'Olio extravergine',qt:'50ml'}],
_dbEntry:{n:'Pasta alla puttanesca (ricetta)',c:'Ricette',src:'RICETTE',k:370,p:12,gs:1.5,g:10,z:4,ch:58,fi:3,ca:55,fe:2.5,mg:40,k2:420,na:850,zn:1,fo:30,se:10,col:8}},

{id:'tpl_1063',nome:'Risotto ai gamberi e lime',nome_en:'Prawn and lime risotto',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere scalogno in olio. Aggiungere gamberi sgusciati e rosolare brevemente, togliere. Tostare il riso, sfumare con vino bianco. Aggiungere brodo di pesce. Mantecare con olio, succo e scorza di lime. Aggiungere i gamberi.',
note_en:'Sauté shallot in oil. Add peeled prawns and brown briefly, remove. Toast rice, deglaze with white wine. Add fish stock. Stir in oil, lime juice and zest. Add prawns.',
ingredienti:[{nome:'Riso Carnaroli',qt:'320g'},{nome:'Gamberi',qt:'300g'},{nome:'Scalogno',qt:'2'},{nome:'Lime',qt:'2'},{nome:'Vino bianco',qt:'100ml'},{nome:'Olio extravergine',qt:'40ml'},{nome:'Brodo di pesce',qt:'1L'},{nome:'Erba cipollina',qt:'15g'}],
_dbEntry:{n:'Risotto ai gamberi e lime (ricetta)',c:'Ricette',src:'RICETTE',k:360,p:17,gs:1,g:7,z:2,ch:54,fi:0.5,ca:70,fe:2,mg:45,k2:380,na:360,zn:1.8,fo:30,se:28,col:115}},

{id:'tpl_1064',nome:'Pasta alla checca',nome_en:'Pasta alla checca',categoria:'Primo piatto',porzioni:4,
note:'Tagliare pomodori a cubetti, condire con aglio, basilico, olio e sale. Marinare 30 minuti a temperatura ambiente. Cuocere la pasta al dente, scolare e condire immediatamente con il sugo freddo. Aggiungere mozzarella a cubetti.',
note_en:'Dice tomatoes, season with garlic, basil, oil and salt. Marinate 30 minutes at room temperature. Cook pasta al dente, drain and immediately dress with cold sauce. Add diced mozzarella.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Pomodori maturi',qt:'500g'},{nome:'Mozzarella',qt:'150g'},{nome:'Basilico',qt:'20g'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Olio extravergine',qt:'60ml'}],
_dbEntry:{n:'Pasta alla checca (ricetta)',c:'Ricette',src:'RICETTE',k:420,p:16,gs:3,g:14,z:4,ch:58,fi:2.5,ca:220,fe:1.5,mg:35,k2:380,na:280,zn:1.5,fo:40,se:10,col:25}},

{id:'tpl_1065',nome:'Pasta con crema di melanzane',nome_en:'Pasta with aubergine cream',categoria:'Primo piatto',porzioni:4,
note:'Grigliare le melanzane, frullarle con aglio, tahini, succo di limone e olio per una crema. Cuocere la pasta al dente. Mantecare con la crema di melanzane, aggiungendo acqua di cottura. Guarnire con pomodorini e menta.',
note_en:'Grill aubergines, blend with garlic, tahini, lemon juice and oil for a cream. Cook pasta al dente. Toss with aubergine cream, adding cooking water. Garnish with cherry tomatoes and mint.',
ingredienti:[{nome:'Pennette',qt:'320g'},{nome:'Melanzane',qt:'500g'},{nome:'Tahini',qt:'30g'},{nome:'Limone',qt:'1'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Olio extravergine',qt:'40ml'},{nome:'Pomodorini',qt:'100g'}],
_dbEntry:{n:'Pasta con crema di melanzane (ricetta)',c:'Ricette',src:'RICETTE',k:390,p:12,gs:1.5,g:11,z:5,ch:60,fi:5,ca:55,fe:2.5,mg:48,k2:420,na:220,zn:1.2,fo:50,se:6,col:0}},

{id:'tpl_1066',nome:'Soup di pomodoro e basilico',nome_en:'Tomato and basil soup',categoria:'Primo piatto',porzioni:4,
note:'Rosolare cipolla e aglio in olio. Aggiungere pomodori pelati e brodo vegetale. Cuocere 20 minuti. Frullare fino a crema liscia. Condire con basilico fresco e olio extravergine. Servire con crostini di pane.',
note_en:'Brown onion and garlic in oil. Add peeled tomatoes and vegetable stock. Cook 20 minutes. Blend to smooth cream. Season with fresh basil and extra virgin olive oil. Serve with bread croutons.',
ingredienti:[{nome:'Pomodori pelati',qt:'800g'},{nome:'Cipolla',qt:'1'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Basilico',qt:'20g'},{nome:'Olio extravergine',qt:'40ml'},{nome:'Brodo vegetale',qt:'400ml'},{nome:'Pane per crostini',qt:'100g'}],
_dbEntry:{n:'Soup di pomodoro e basilico (ricetta)',c:'Ricette',src:'RICETTE',k:220,p:5,gs:1,g:8,z:8,ch:32,fi:3.5,ca:50,fe:2,mg:30,k2:480,na:340,zn:0.5,fo:30,se:5,col:0}},

{id:'tpl_1067',nome:'Pasta con il baccala',nome_en:'Pasta with salt cod',categoria:'Primo piatto',porzioni:4,
note:'Dissalare il baccala 48 ore cambiando l acqua. Soffriggere aglio, cipolla e pomodorini. Aggiungere il baccala a pezzi e cuocere 15 minuti. Cuocere la pasta al dente. Saltare nel sugo con prezzemolo e olive.',
note_en:'Desalt cod for 48 hours changing water. Sauté garlic, onion and cherry tomatoes. Add cod pieces and cook 15 minutes. Cook pasta al dente. Toss in sauce with parsley and olives.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Baccala dissalato',qt:'400g'},{nome:'Pomodorini',qt:'250g'},{nome:'Olive nere',qt:'50g'},{nome:'Aglio',qt:'3 spicchi'},{nome:'Olio extravergine',qt:'50ml'},{nome:'Prezzemolo',qt:'15g'}],
_dbEntry:{n:'Pasta con il baccala (ricetta)',c:'Ricette',src:'RICETTE',k:370,p:22,gs:1.5,g:9,z:3,ch:52,fi:2.5,ca:60,fe:2,mg:50,k2:520,na:680,zn:1.5,fo:30,se:28,col:45}},

{id:'tpl_1068',nome:'Risotto alla crema di scampi',nome_en:'Scampi cream risotto',categoria:'Primo piatto',porzioni:4,
note:'Sgusciare gli scampi. Preparare un fumetto con i carapaci. Soffriggere scalogno, tostare il riso, sfumare con brandy. Aggiungere il fumetto di scampi. Mantecare con burro e la polpa degli scampi saltata brevemente.',
note_en:'Shell langoustines. Make a bisque with the shells. Sauté shallot, toast rice, flambé with brandy. Add langoustine bisque. Stir in butter and briefly sautéed langoustine flesh.',
ingredienti:[{nome:'Riso Carnaroli',qt:'320g'},{nome:'Scampi',qt:'500g'},{nome:'Scalogno',qt:'2'},{nome:'Brandy',qt:'50ml'},{nome:'Burro',qt:'40g'},{nome:'Pomodori',qt:'100g'},{nome:'Erbe aromatiche',qt:'q.b.'}],
_dbEntry:{n:'Risotto alla crema di scampi (ricetta)',c:'Ricette',src:'RICETTE',k:380,p:22,gs:3,g:9,z:2,ch:52,fi:0.5,ca:80,fe:2,mg:50,k2:420,na:480,zn:2,fo:40,se:30,col:140}},

{id:'tpl_1069',nome:'Pasta fredda al pesto e pomodorini',nome_en:'Cold pasta with pesto and cherry tomatoes',categoria:'Primo piatto',porzioni:4,
note:'Cuocere la pasta al dente, sciacquare con acqua fredda. Condire con pesto genovese, pomodorini halved, olive e mozzarella. Lasciare riposare in frigorifero 30 minuti prima di servire.',
note_en:'Cook pasta al dente, rinse with cold water. Dress with Genoese pesto, halved cherry tomatoes, olives and mozzarella. Rest in refrigerator 30 minutes before serving.',
ingredienti:[{nome:'Fusilli',qt:'320g'},{nome:'Pesto genovese',qt:'80g'},{nome:'Pomodorini',qt:'200g'},{nome:'Mozzarella',qt:'125g'},{nome:'Olive',qt:'50g'},{nome:'Olio extravergine',qt:'20ml'}],
_dbEntry:{n:'Pasta fredda al pesto e pomodorini (ricetta)',c:'Ricette',src:'RICETTE',k:420,p:16,gs:4,g:16,z:4,ch:56,fi:3,ca:200,fe:2,mg:38,k2:300,na:420,zn:1.5,fo:40,se:8,col:20}},

{id:'tpl_1070',nome:'Pasta con crema di piselli e menta',nome_en:'Pasta with pea and mint cream',categoria:'Primo piatto',porzioni:4,
note:'Cuocere i piselli in acqua salata. Frullarli con menta, parmigiano e olio fino a crema. Cuocere la pasta al dente. Mantecare con la crema di piselli aggiungendo acqua di cottura. Guarnire con piselli interi e menta fresca.',
note_en:'Cook peas in salted water. Blend with mint, parmesan and oil to a cream. Cook pasta al dente. Toss with pea cream adding cooking water. Garnish with whole peas and fresh mint.',
ingredienti:[{nome:'Mezze penne',qt:'320g'},{nome:'Piselli freschi',qt:'500g'},{nome:'Menta fresca',qt:'15g'},{nome:'Parmigiano',qt:'50g'},{nome:'Olio extravergine',qt:'40ml'}],
_dbEntry:{n:'Pasta con crema di piselli e menta (ricetta)',c:'Ricette',src:'RICETTE',k:370,p:16,gs:2,g:10,z:5,ch:58,fi:7,ca:80,fe:2.5,mg:45,k2:380,na:200,zn:1.2,fo:70,se:5,col:5}},

{id:'tpl_1071',nome:'Fusilli con pomodorini e ricotta',nome_en:'Fusilli with cherry tomatoes and ricotta',categoria:'Primo piatto',porzioni:4,
note:'Saltare i pomodorini in olio con aglio fino a far scoppiare. Cuocere i fusilli al dente. Scolare e mantecare con i pomodorini, ricotta fresca, basilico e olio. Aggiungere parmigiano se gradito.',
note_en:'Sauté cherry tomatoes in oil with garlic until they burst. Cook fusilli al dente. Drain and toss with cherry tomatoes, fresh ricotta, basil and oil. Add parmesan if desired.',
ingredienti:[{nome:'Fusilli',qt:'320g'},{nome:'Pomodorini',qt:'300g'},{nome:'Ricotta fresca',qt:'200g'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Basilico',qt:'15g'},{nome:'Olio extravergine',qt:'40ml'}],
_dbEntry:{n:'Fusilli con pomodorini e ricotta (ricetta)',c:'Ricette',src:'RICETTE',k:400,p:15,gs:2.5,g:11,z:4,ch:58,fi:2.5,ca:150,fe:1.5,mg:35,k2:320,na:220,zn:1,fo:35,se:8,col:18}},

{id:'tpl_1072',nome:'Pasta al pesto di pistacchi',nome_en:'Pasta with pistachio pesto',categoria:'Primo piatto',porzioni:4,
note:'Frullare pistacchi non salati tostati con aglio, basilico, parmigiano e olio per fare il pesto. Cuocere la pasta al dente. Mantecare con il pesto di pistacchi e acqua di cottura.',
note_en:'Blend toasted unsalted pistachios with garlic, basil, parmesan and oil to make pesto. Cook pasta al dente. Toss with pistachio pesto and cooking water.',
ingredienti:[{nome:'Linguine',qt:'320g'},{nome:'Pistacchi non salati',qt:'100g'},{nome:'Basilico',qt:'20g'},{nome:'Parmigiano',qt:'50g'},{nome:'Aglio',qt:'1 spicchio'},{nome:'Olio extravergine',qt:'80ml'}],
_dbEntry:{n:'Pasta al pesto di pistacchi (ricetta)',c:'Ricette',src:'RICETTE',k:480,p:16,gs:3,g:22,z:3,ch:56,fi:3.5,ca:120,fe:2.5,mg:60,k2:500,na:180,zn:1.5,fo:35,se:5,col:5}},

{id:'tpl_1073',nome:'Tagliatelle al tartufo nero',nome_en:'Tagliatelle with black truffle',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere aglio in burro e olio. Aggiungere tartufo nero grattugiato o a lamelle. Cuocere le tagliatelle fresche. Mantecare con burro, tartufo e parmigiano. Servire immediatamente.',
note_en:'Sauté garlic in butter and oil. Add grated or sliced black truffle. Cook fresh tagliatelle. Toss with butter, truffle and parmesan. Serve immediately.',
ingredienti:[{nome:'Tagliatelle fresche',qt:'400g'},{nome:'Tartufo nero',qt:'40g'},{nome:'Burro',qt:'60g'},{nome:'Aglio',qt:'1 spicchio'},{nome:'Parmigiano',qt:'60g'},{nome:'Olio extravergine',qt:'20ml'}],
_dbEntry:{n:'Tagliatelle al tartufo nero (ricetta)',c:'Ricette',src:'RICETTE',k:430,p:15,gs:9,g:18,z:2,ch:56,fi:1.5,ca:130,fe:2,mg:25,k2:200,na:350,zn:1.5,fo:25,se:5,col:120}},

{id:'tpl_1074',nome:'Zuppa di zucca e zenzero',nome_en:'Pumpkin and ginger soup',categoria:'Primo piatto',porzioni:4,
note:'Rosolare cipolla in olio. Aggiungere zucca a cubetti, zenzero fresco grattugiato e brodo vegetale. Cuocere 25 minuti. Frullare fino a crema vellutata. Aggiustare di sale. Servire con panna acida e semi di zucca tostati.',
note_en:'Brown onion in oil. Add diced pumpkin, fresh grated ginger and vegetable stock. Cook 25 minutes. Blend to velvety cream. Season with salt. Serve with sour cream and toasted pumpkin seeds.',
ingredienti:[{nome:'Zucca',qt:'600g'},{nome:'Zenzero fresco',qt:'20g'},{nome:'Cipolla',qt:'1'},{nome:'Brodo vegetale',qt:'800ml'},{nome:'Panna acida',qt:'50g'},{nome:'Semi di zucca',qt:'30g'},{nome:'Olio extravergine',qt:'30ml'}],
_dbEntry:{n:'Zuppa di zucca e zenzero (ricetta)',c:'Ricette',src:'RICETTE',k:200,p:5,gs:1.5,g:8,z:8,ch:28,fi:3,ca:55,fe:1.5,mg:30,k2:560,na:320,zn:0.8,fo:35,se:5,col:8}},

{id:'tpl_1075',nome:'Pasta con cozze e zafferano',nome_en:'Pasta with mussels and saffron',categoria:'Primo piatto',porzioni:4,
note:'Far aprire le cozze in padella con aglio e vino bianco. Sgusciare la meta. Soffriggere scalogno, aggiungere zafferano sciolto in brodo. Cuocere gli spaghetti. Saltare con le cozze e il loro liquido filtrato.',
note_en:'Open mussels in pan with garlic and white wine. Shell half. Sauté shallot, add saffron dissolved in stock. Cook spaghetti. Toss with mussels and their filtered liquid.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Cozze',qt:'800g'},{nome:'Scalogno',qt:'2'},{nome:'Vino bianco',qt:'150ml'},{nome:'Zafferano',qt:'1 bustina'},{nome:'Prezzemolo',qt:'15g'},{nome:'Olio extravergine',qt:'40ml'}],
_dbEntry:{n:'Pasta con cozze e zafferano (ricetta)',c:'Ricette',src:'RICETTE',k:360,p:18,gs:1.5,g:9,z:2,ch:52,fi:2,ca:80,fe:4,mg:50,k2:380,na:480,zn:2.5,fo:35,se:30,col:38}},

{id:'tpl_1076',nome:'Risotto al caprino e noci',nome_en:'Goat cheese and walnut risotto',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere scalogno in burro. Tostare il riso, sfumare con vino bianco. Aggiungere brodo vegetale. A cottura quasi ultimata aggiungere caprino a pezzi e noci tritate. Mantecare con burro. Servire con miele e noci intere.',
note_en:'Sauté shallot in butter. Toast rice, deglaze with white wine. Add vegetable stock. Near end of cooking add crumbled goat cheese and chopped walnuts. Stir in butter. Serve with honey and whole walnuts.',
ingredienti:[{nome:'Riso Carnaroli',qt:'320g'},{nome:'Caprino fresco',qt:'150g'},{nome:'Noci',qt:'60g'},{nome:'Scalogno',qt:'2'},{nome:'Burro',qt:'40g'},{nome:'Miele',qt:'20g'},{nome:'Brodo vegetale',qt:'1L'}],
_dbEntry:{n:'Risotto al caprino e noci (ricetta)',c:'Ricette',src:'RICETTE',k:430,p:14,gs:6,g:16,z:4,ch:56,fi:1.5,ca:120,fe:1.5,mg:40,k2:280,na:350,zn:1.5,fo:30,se:6,col:28}},

{id:'tpl_1077',nome:'Pasta e lenticchie',nome_en:'Pasta and lentils',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere sedano, carota e cipolla. Aggiungere lenticchie rosse o verdi e brodo. Cuocere 20 minuti. Aggiungere pasta corta e cuocere. Il piatto deve rimanere semi-brodoso. Condire con olio crudo, aglio e peperoncino.',
note_en:'Sauté celery, carrot and onion. Add red or green lentils and stock. Cook 20 minutes. Add short pasta and cook. Dish should remain semi-soupy. Season with raw oil, garlic and chilli.',
ingredienti:[{nome:'Pasta corta',qt:'200g'},{nome:'Lenticchie',qt:'250g'},{nome:'Cipolla',qt:'1'},{nome:'Carota',qt:'1'},{nome:'Sedano',qt:'1 costa'},{nome:'Brodo vegetale',qt:'1L'},{nome:'Olio extravergine',qt:'40ml'}],
_dbEntry:{n:'Pasta e lenticchie (ricetta)',c:'Ricette',src:'RICETTE',k:310,p:15,gs:0.8,g:6,z:3,ch:52,fi:9,ca:55,fe:4,mg:60,k2:580,na:300,zn:2,fo:145,se:6,col:0}},

{id:'tpl_1078',nome:'Pasta con bottarga di muggine',nome_en:'Pasta with grey mullet bottarga',categoria:'Primo piatto',porzioni:4,
note:'Cuocere gli spaghetti al dente. Soffriggere aglio in olio. Scolare la pasta e mantecare con olio, aglio e bottarga grattugiata abbondante. Aggiungere poco prezzemolo e scorza di limone. Servire con bottarga a lamelle.',
note_en:'Cook spaghetti al dente. Sauté garlic in oil. Drain pasta and toss with oil, garlic and generous grated bottarga. Add a little parsley and lemon zest. Serve with bottarga in slices.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Bottarga di muggine',qt:'60g'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Olio extravergine',qt:'60ml'},{nome:'Limone',qt:'1'},{nome:'Prezzemolo',qt:'10g'}],
_dbEntry:{n:'Pasta con bottarga di muggine (ricetta)',c:'Ricette',src:'RICETTE',k:420,p:18,gs:2,g:14,z:1,ch:56,fi:1,ca:50,fe:2,mg:38,k2:280,na:680,zn:1.5,fo:20,se:30,col:110}},

{id:'tpl_1079',nome:'Vellutata di asparagi',nome_en:'Asparagus velouté',categoria:'Primo piatto',porzioni:4,
note:'Lessare gli asparagi in acqua salata, tenere le punte. Frullare i gambi con scalogno soffritto, panna e brodo. Portare a consistenza vellutata. Aggiustare di sale e pepe. Servire con le punte e crostini.',
note_en:'Boil asparagus in salted water, keep tips. Blend stalks with sautéed shallot, cream and stock. Bring to velvety consistency. Season with salt and pepper. Serve with tips and croutons.',
ingredienti:[{nome:'Asparagi',qt:'600g'},{nome:'Scalogno',qt:'2'},{nome:'Panna da cucina',qt:'100ml'},{nome:'Brodo vegetale',qt:'500ml'},{nome:'Burro',qt:'30g'},{nome:'Pane per crostini',qt:'80g'}],
_dbEntry:{n:'Vellutata di asparagi (ricetta)',c:'Ricette',src:'RICETTE',k:220,p:7,gs:4,g:11,z:5,ch:22,fi:3.5,ca:60,fe:2.5,mg:25,k2:380,na:350,zn:0.8,fo:90,se:5,col:35}},

{id:'tpl_1080',nome:'Pasta ai quattro formaggi',nome_en:'Pasta with four cheeses',categoria:'Primo piatto',porzioni:4,
note:'Sciogliere in padella gorgonzola, taleggio, fontina e parmigiano con un pocod di panna. Mescolare fino a crema omogenea. Cuocere la pasta al dente. Mantecare con la crema di formaggi e acqua di cottura.',
note_en:'Melt gorgonzola, taleggio, fontina and parmesan in a pan with a little cream. Stir to smooth cream. Cook pasta al dente. Toss with cheese cream and cooking water.',
ingredienti:[{nome:'Rigatoni',qt:'320g'},{nome:'Gorgonzola',qt:'80g'},{nome:'Taleggio',qt:'80g'},{nome:'Fontina',qt:'80g'},{nome:'Parmigiano',qt:'40g'},{nome:'Panna da cucina',qt:'80ml'}],
_dbEntry:{n:'Pasta ai quattro formaggi (ricetta)',c:'Ricette',src:'RICETTE',k:490,p:22,gs:11,g:20,z:3,ch:55,fi:1,ca:420,fe:1.5,mg:30,k2:200,na:780,zn:3,fo:20,se:10,col:75}},

{id:'tpl_1081',nome:'Pasta con noci e gorgonzola',nome_en:'Pasta with walnuts and gorgonzola',categoria:'Primo piatto',porzioni:4,
note:'Sciogliere il gorgonzola in panna. Tostare le noci in padella. Cuocere la pasta al dente. Mantecare con la crema di gorgonzola e le noci. Guarnire con rucola e pepe.',
note_en:'Melt gorgonzola in cream. Toast walnuts in pan. Cook pasta al dente. Toss with gorgonzola cream and walnuts. Garnish with rocket and pepper.',
ingredienti:[{nome:'Rigatoni',qt:'320g'},{nome:'Gorgonzola',qt:'150g'},{nome:'Noci',qt:'80g'},{nome:'Panna da cucina',qt:'100ml'},{nome:'Rucola',qt:'30g'}],
_dbEntry:{n:'Pasta con noci e gorgonzola (ricetta)',c:'Ricette',src:'RICETTE',k:490,p:18,gs:9,g:22,z:2.5,ch:54,fi:2.5,ca:220,fe:1.5,mg:48,k2:300,na:600,zn:2,fo:28,se:8,col:45}},

{id:'tpl_1082',nome:'Zuppa di pesce alla livornese',nome_en:'Livornese fish soup',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere cipolla, aglio e peperoncino in olio. Aggiungere pomodori, cacciucco o misto di pesce e brodo. Cuocere 20 minuti. Servire su pane tostato strofinato con aglio.',
note_en:'Sauté onion, garlic and chilli in oil. Add tomatoes, mixed fish and stock. Cook 20 minutes. Serve on toasted bread rubbed with garlic.',
ingredienti:[{nome:'Pesce misto',qt:'600g'},{nome:'Pomodori pelati',qt:'400g'},{nome:'Cipolla',qt:'1'},{nome:'Aglio',qt:'3 spicchi'},{nome:'Peperoncino',qt:'2'},{nome:'Olio extravergine',qt:'50ml'},{nome:'Brodo di pesce',qt:'500ml'},{nome:'Pane',qt:'150g'}],
_dbEntry:{n:'Zuppa di pesce alla livornese (ricetta)',c:'Ricette',src:'RICETTE',k:300,p:28,gs:2,g:10,z:4,ch:22,fi:2,ca:80,fe:2.5,mg:50,k2:550,na:480,zn:2,fo:35,se:35,col:90}},

{id:'tpl_1083',nome:'Pasta con crema di sedano rapa',nome_en:'Pasta with celeriac cream',categoria:'Primo piatto',porzioni:4,
note:'Cuocere sedano rapa a cubetti in brodo fino a morbido. Frullare con parmigiano e olio fino a crema. Cuocere la pasta al dente. Mantecare con la crema di sedano rapa. Guarnire con nocciole tostate e prezzemolo.',
note_en:'Cook diced celeriac in stock until soft. Blend with parmesan and oil to a cream. Cook pasta al dente. Toss with celeriac cream. Garnish with toasted hazelnuts and parsley.',
ingredienti:[{nome:'Penne',qt:'320g'},{nome:'Sedano rapa',qt:'400g'},{nome:'Parmigiano',qt:'50g'},{nome:'Nocciole tostate',qt:'40g'},{nome:'Brodo vegetale',qt:'400ml'},{nome:'Olio extravergine',qt:'40ml'}],
_dbEntry:{n:'Pasta con crema di sedano rapa (ricetta)',c:'Ricette',src:'RICETTE',k:400,p:14,gs:2,g:13,z:3,ch:58,fi:3,ca:110,fe:2,mg:40,k2:380,na:280,zn:1.5,fo:35,se:6,col:5}},

{id:'tpl_1084',nome:'Pasta e ceci speziata',nome_en:'Spiced pasta and chickpeas',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere cipolla, aglio, cumino, curcuma e peperoncino in olio. Aggiungere ceci e pomodori. Cuocere 15 minuti. Aggiungere pasta corta e brodo. Cuocere al dente. Servire con foglie di coriandolo fresco.',
note_en:'Sauté onion, garlic, cumin, turmeric and chilli in oil. Add chickpeas and tomatoes. Cook 15 minutes. Add short pasta and stock. Cook al dente. Serve with fresh coriander leaves.',
ingredienti:[{nome:'Pasta corta',qt:'200g'},{nome:'Ceci cotti',qt:'400g'},{nome:'Pomodori',qt:'200g'},{nome:'Cipolla',qt:'1'},{nome:'Curcuma',qt:'1 cucchiaino'},{nome:'Cumino',qt:'1 cucchiaino'},{nome:'Brodo vegetale',qt:'600ml'},{nome:'Olio extravergine',qt:'30ml'}],
_dbEntry:{n:'Pasta e ceci speziata (ricetta)',c:'Ricette',src:'RICETTE',k:320,p:14,gs:0.8,g:6,z:3,ch:54,fi:10,ca:65,fe:4,mg:68,k2:560,na:300,zn:2,fo:130,se:6,col:0}},

{id:'tpl_1085',nome:'Spaghetti al cartoccio con frutti di mare',nome_en:'Spaghetti en papillote with seafood',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere aglio in olio, aggiungere misto di frutti di mare, vino bianco e pomodorini. Cuocere 5 minuti. Mescolare con spaghetti a meta cottura. Chiudere in carta forno e cuocere in forno a 200 C per 12 minuti.',
note_en:'Sauté garlic in oil, add mixed seafood, white wine and cherry tomatoes. Cook 5 minutes. Mix with halfway-cooked spaghetti. Seal in baking paper and bake at 200 C for 12 minutes.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Frutti di mare misti',qt:'500g'},{nome:'Pomodorini',qt:'200g'},{nome:'Vino bianco',qt:'100ml'},{nome:'Aglio',qt:'3 spicchi'},{nome:'Prezzemolo',qt:'15g'},{nome:'Olio extravergine',qt:'40ml'}],
_dbEntry:{n:'Spaghetti al cartoccio con frutti di mare (ricetta)',c:'Ricette',src:'RICETTE',k:380,p:22,gs:1.5,g:9,z:3,ch:52,fi:2,ca:80,fe:3,mg:48,k2:420,na:480,zn:2,fo:30,se:30,col:80}},

{id:'tpl_1086',nome:'Pasta con broccoletti e salsiccia',nome_en:'Pasta with turnip tops and sausage',categoria:'Primo piatto',porzioni:4,
note:'Lessare i broccoletti in acqua salata. Soffriggere la salsiccia sbriciolata con aglio e peperoncino. Cuocere le orecchiette nell acqua dei broccoletti. Saltare tutto insieme con olio abbondante.',
note_en:'Boil turnip tops in salted water. Brown crumbled sausage with garlic and chilli. Cook orecchiette in the turnip top water. Toss everything together with plenty of oil.',
ingredienti:[{nome:'Orecchiette',qt:'320g'},{nome:'Cime di rapa',qt:'400g'},{nome:'Salsiccia',qt:'200g'},{nome:'Aglio',qt:'3 spicchi'},{nome:'Peperoncino',qt:'1'},{nome:'Olio extravergine',qt:'50ml'}],
_dbEntry:{n:'Pasta con broccoletti e salsiccia (ricetta)',c:'Ricette',src:'RICETTE',k:450,p:20,gs:5,g:16,z:3,ch:56,fi:5,ca:120,fe:3,mg:55,k2:500,na:480,zn:2.5,fo:80,se:15,col:45}},

{id:'tpl_1087',nome:'Minestrone estivo con basilico',nome_en:'Summer minestrone with basil',categoria:'Primo piatto',porzioni:4,
note:'Cuocere zucchine, pomodori, melanzane, fagiolini e cipolla in brodo vegetale. Aggiungere pasta corta. Cuocere al dente. Condire con pesto di basilico fresco. Servire tiepido o freddo.',
note_en:'Cook courgettes, tomatoes, aubergines, green beans and onion in vegetable stock. Add short pasta. Cook al dente. Dress with fresh basil pesto. Serve warm or cold.',
ingredienti:[{nome:'Ditalini',qt:'150g'},{nome:'Zucchine',qt:'200g'},{nome:'Pomodori',qt:'200g'},{nome:'Melanzane',qt:'150g'},{nome:'Fagiolini',qt:'150g'},{nome:'Pesto fresco',qt:'60g'},{nome:'Brodo vegetale',qt:'1.2L'}],
_dbEntry:{n:'Minestrone estivo con basilico (ricetta)',c:'Ricette',src:'RICETTE',k:270,p:9,gs:0.8,g:7,z:5,ch:43,fi:6,ca:60,fe:2,mg:42,k2:450,na:310,zn:1,fo:55,se:5,col:2}},

{id:'tpl_1088',nome:'Risotto con spinaci e fontina',nome_en:'Risotto with spinach and fontina',categoria:'Primo piatto',porzioni:4,
note:'Lessare gli spinaci, strizzarli e frullarne meta. Soffriggere scalogno in burro, tostare il riso, sfumare con vino. Aggiungere brodo e la crema di spinaci. Mantecare con burro e fontina. Aggiungere gli spinaci interi rimasti.',
note_en:'Boil spinach, squeeze out water and blend half. Sauté shallot in butter, toast rice, deglaze with wine. Add stock and spinach cream. Stir in butter and fontina. Add remaining whole spinach.',
ingredienti:[{nome:'Riso Carnaroli',qt:'320g'},{nome:'Spinaci freschi',qt:'400g'},{nome:'Fontina',qt:'100g'},{nome:'Scalogno',qt:'2'},{nome:'Burro',qt:'40g'},{nome:'Vino bianco',qt:'100ml'},{nome:'Brodo vegetale',qt:'1L'}],
_dbEntry:{n:'Risotto con spinaci e fontina (ricetta)',c:'Ricette',src:'RICETTE',k:380,p:14,gs:6,g:12,z:3,ch:55,fi:3,ca:220,fe:2.5,mg:45,k2:350,na:480,zn:1.8,fo:120,se:8,col:40}},

{id:'tpl_1089',nome:'Pasta con l aglio e olio',nome_en:'Pasta with garlic and oil',categoria:'Primo piatto',porzioni:4,
note:'Affettare aglio finissimo e dorarlo in abbondante olio a fuoco dolcissimo. Aggiungere peperoncino. Cuocere gli spaghetti al dente, tenere acqua di cottura. Mantecare aglio olio e peperoncino con la pasta aggiungendo acqua. Finire con prezzemolo abbondante.',
note_en:'Slice garlic very thin and brown in plenty of oil on very low heat. Add chilli. Cook spaghetti al dente, keep cooking water. Toss garlic oil and chilli with pasta adding water. Finish with plenty of parsley.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Aglio',qt:'6 spicchi'},{nome:'Peperoncino',qt:'2'},{nome:'Olio extravergine',qt:'80ml'},{nome:'Prezzemolo',qt:'20g'}],
_dbEntry:{n:'Pasta con l aglio e olio (ricetta)',c:'Ricette',src:'RICETTE',k:420,p:11,gs:1.5,g:16,z:1,ch:60,fi:1.5,ca:30,fe:2,mg:35,k2:220,na:120,zn:0.8,fo:20,se:6,col:0}},

{id:'tpl_1090',nome:'Trofie al pesto con fagiolini e patate',nome_en:'Trofie pesto with green beans and potatoes',categoria:'Primo piatto',porzioni:4,
note:'Lessare le patate a cubetti e i fagiolini nella stessa acqua salata. Cuocere le trofie con le patate. Scolare tutto. Condire con pesto genovese, parmigiano e pecorino. Amalgamare bene.',
note_en:'Boil diced potatoes and green beans in the same salted water. Cook trofie with potatoes. Drain everything. Dress with Genoese pesto, parmesan and pecorino. Mix well.',
ingredienti:[{nome:'Trofie',qt:'320g'},{nome:'Patate',qt:'200g'},{nome:'Fagiolini',qt:'150g'},{nome:'Pesto genovese',qt:'100g'},{nome:'Parmigiano',qt:'30g'},{nome:'Pecorino',qt:'20g'}],
_dbEntry:{n:'Trofie al pesto con fagiolini e patate (ricetta)',c:'Ricette',src:'RICETTE',k:430,p:14,gs:3,g:16,z:3,ch:62,fi:5,ca:130,fe:2,mg:48,k2:420,na:350,zn:1.2,fo:50,se:6,col:6}},

{id:'tpl_1091',nome:'Pasta con sugo di pomodoro e basilico',nome_en:'Pasta with tomato and basil sauce',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere aglio in olio, aggiungere pomodori pelati e schiacciare. Cuocere 20 minuti. Aggiungere basilico fresco. Cuocere i rigatoni al dente. Condire con il sugo e parmigiano.',
note_en:'Sauté garlic in oil, add peeled tomatoes and crush. Cook 20 minutes. Add fresh basil. Cook rigatoni al dente. Dress with sauce and parmesan.',
ingredienti:[{nome:'Rigatoni',qt:'320g'},{nome:'Pomodori pelati',qt:'400g'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Basilico',qt:'20g'},{nome:'Olio extravergine',qt:'40ml'},{nome:'Parmigiano',qt:'40g'}],
_dbEntry:{n:'Pasta con sugo di pomodoro e basilico (ricetta)',c:'Ricette',src:'RICETTE',k:370,p:13,gs:1,g:8,z:5,ch:60,fi:2.5,ca:90,fe:2,mg:35,k2:380,na:250,zn:1,fo:30,se:7,col:5}},

{id:'tpl_1092',nome:'Vellutata di carote e zenzero',nome_en:'Carrot and ginger velouté',categoria:'Primo piatto',porzioni:4,
note:'Rosolare cipolla in olio. Aggiungere carote a pezzi e zenzero grattugiato. Versare brodo vegetale e cuocere 25 minuti. Frullare con latte di cocco. Aggiustare di sale e servire con semi di sesamo tostati.',
note_en:'Brown onion in oil. Add carrot pieces and grated ginger. Pour in vegetable stock and cook 25 minutes. Blend with coconut milk. Season with salt and serve with toasted sesame seeds.',
ingredienti:[{nome:'Carote',qt:'600g'},{nome:'Cipolla',qt:'1'},{nome:'Zenzero fresco',qt:'20g'},{nome:'Latte di cocco',qt:'100ml'},{nome:'Brodo vegetale',qt:'600ml'},{nome:'Semi di sesamo',qt:'20g'},{nome:'Olio extravergine',qt:'20ml'}],
_dbEntry:{n:'Vellutata di carote e zenzero (ricetta)',c:'Ricette',src:'RICETTE',k:180,p:3,gs:3,g:7,z:10,ch:26,fi:5,ca:55,fe:1.5,mg:30,k2:580,na:320,zn:0.5,fo:30,se:4,col:0}},

{id:'tpl_1093',nome:'Pasta con sugo di peperoni e pomodoro',nome_en:'Pasta with pepper and tomato sauce',categoria:'Primo piatto',porzioni:4,
note:'Grigliare i peperoni e spellarli. Soffriggere cipolla, aggiungere peperoni e pomodori. Cuocere 20 minuti. Frullare meta del sugo per renderlo cremoso. Cuocere la pasta al dente e condire.',
note_en:'Grill peppers and peel. Sauté onion, add peppers and tomatoes. Cook 20 minutes. Blend half the sauce to make it creamy. Cook pasta al dente and dress.',
ingredienti:[{nome:'Fusilli',qt:'320g'},{nome:'Peperoni rossi',qt:'3'},{nome:'Pomodori pelati',qt:'300g'},{nome:'Cipolla',qt:'1'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Olio extravergine',qt:'40ml'},{nome:'Basilico',qt:'10g'}],
_dbEntry:{n:'Pasta con sugo di peperoni e pomodoro (ricetta)',c:'Ricette',src:'RICETTE',k:360,p:11,gs:1,g:8,z:7,ch:60,fi:4,ca:45,fe:2,mg:42,k2:450,na:240,zn:0.9,fo:50,se:6,col:0}},

{id:'tpl_1094',nome:'Risotto con gamberetti e limone',nome_en:'Risotto with shrimps and lemon',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere scalogno in olio. Aggiungere i gamberetti sgusciati, sfumare con vino bianco. Togliere i gamberetti. Tostare il riso nella base, aggiungere brodo di pesce. Mantecare con olio, succo di limone e scorza. Rimettere i gamberetti.',
note_en:'Sauté shallot in oil. Add peeled shrimps, deglaze with white wine. Remove shrimps. Toast rice in base, add fish stock. Stir in oil, lemon juice and zest. Return shrimps.',
ingredienti:[{nome:'Riso Carnaroli',qt:'320g'},{nome:'Gamberetti',qt:'300g'},{nome:'Scalogno',qt:'2'},{nome:'Limone',qt:'2'},{nome:'Vino bianco',qt:'100ml'},{nome:'Olio extravergine',qt:'40ml'},{nome:'Brodo di pesce',qt:'1L'}],
_dbEntry:{n:'Risotto con gamberetti e limone (ricetta)',c:'Ricette',src:'RICETTE',k:360,p:16,gs:1,g:7,z:2,ch:54,fi:0.5,ca:70,fe:1.8,mg:42,k2:360,na:360,zn:1.5,fo:28,se:25,col:105}},

{id:'tpl_1095',nome:'Pasta con agnello e rosmarino',nome_en:'Pasta with lamb and rosemary',categoria:'Primo piatto',porzioni:4,
note:'Rosolare pezzi di agnello con rosmarino, aglio e cipolla. Sfumare con vino rosso. Aggiungere pomodori e cuocere 45 minuti. Cuocere la pasta al dente. Condire con il sugo di agnello e pecorino.',
note_en:'Brown lamb pieces with rosemary, garlic and onion. Deglaze with red wine. Add tomatoes and cook 45 minutes. Cook pasta al dente. Dress with lamb sauce and pecorino.',
ingredienti:[{nome:'Mezze maniche',qt:'320g'},{nome:'Agnello',qt:'300g'},{nome:'Pomodori pelati',qt:'300g'},{nome:'Rosmarino',qt:'2 rametti'},{nome:'Cipolla',qt:'1'},{nome:'Vino rosso',qt:'100ml'},{nome:'Pecorino',qt:'40g'}],
_dbEntry:{n:'Pasta con agnello e rosmarino (ricetta)',c:'Ricette',src:'RICETTE',k:440,p:24,gs:5,g:14,z:4,ch:54,fi:2.5,ca:100,fe:3,mg:42,k2:450,na:400,zn:4,fo:35,se:18,col:70}},

{id:'tpl_1096',nome:'Zuppa di verza e patate',nome_en:'Savoy cabbage and potato soup',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere pancetta con cipolla. Aggiungere verza a strisce, patate a cubetti e brodo. Cuocere 30 minuti. Aggiungere pastina o orzo. Servire con parmigiano e olio crudo.',
note_en:'Brown pancetta with onion. Add shredded savoy cabbage, diced potatoes and stock. Cook 30 minutes. Add pastina or barley. Serve with parmesan and raw oil.',
ingredienti:[{nome:'Pastina',qt:'120g'},{nome:'Verza',qt:'400g'},{nome:'Patate',qt:'300g'},{nome:'Pancetta',qt:'80g'},{nome:'Cipolla',qt:'1'},{nome:'Brodo vegetale',qt:'1.2L'},{nome:'Parmigiano',qt:'40g'}],
_dbEntry:{n:'Zuppa di verza e patate (ricetta)',c:'Ricette',src:'RICETTE',k:290,p:12,gs:2,g:7,z:4,ch:44,fi:5,ca:100,fe:1.5,mg:38,k2:580,na:420,zn:1,fo:55,se:5,col:18}},

{id:'tpl_1097',nome:'Pasta con sugo alla pescatora',nome_en:'Pasta with fisherman sauce',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere aglio in olio, aggiungere pomodorini, vino bianco e misto di cozze, vongole, gamberi e calamari. Coprire e cuocere 10 minuti. Cuocere gli spaghetti al dente. Saltare nel sugo con prezzemolo abbondante.',
note_en:'Sauté garlic in oil, add cherry tomatoes, white wine and mixed mussels, clams, prawns and squid. Cover and cook 10 minutes. Cook spaghetti al dente. Toss in sauce with plenty of parsley.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Cozze',qt:'300g'},{nome:'Vongole',qt:'300g'},{nome:'Gamberi',qt:'200g'},{nome:'Calamari',qt:'150g'},{nome:'Pomodorini',qt:'200g'},{nome:'Vino bianco',qt:'150ml'},{nome:'Prezzemolo',qt:'20g'},{nome:'Olio extravergine',qt:'50ml'}],
_dbEntry:{n:'Pasta con sugo alla pescatora (ricetta)',c:'Ricette',src:'RICETTE',k:380,p:25,gs:1.5,g:9,z:3,ch:52,fi:2,ca:100,fe:4,mg:55,k2:480,na:500,zn:3,fo:40,se:35,col:95}},

{id:'tpl_1098',nome:'Riso integrale con verdure e curcuma',nome_en:'Brown rice with vegetables and turmeric',categoria:'Primo piatto',porzioni:4,
note:'Cuocere il riso integrale 35 minuti in acqua salata. Saltare le verdure con curcuma, zenzero e olio. Mescolare riso e verdure. Aggiustare di sale. Servire con salsa di yogurt e coriandolo.',
note_en:'Cook brown rice 35 minutes in salted water. Sauté vegetables with turmeric, ginger and oil. Mix rice and vegetables. Season with salt. Serve with yoghurt sauce and coriander.',
ingredienti:[{nome:'Riso integrale',qt:'300g'},{nome:'Verdure miste',qt:'350g'},{nome:'Curcuma',qt:'1 cucchiaino'},{nome:'Zenzero fresco',qt:'15g'},{nome:'Yogurt naturale',qt:'100g'},{nome:'Olio extravergine',qt:'30ml'},{nome:'Coriandolo fresco',qt:'10g'}],
_dbEntry:{n:'Riso integrale con verdure e curcuma (ricetta)',c:'Ricette',src:'RICETTE',k:310,p:8,gs:0.8,g:6,z:5,ch:56,fi:5,ca:55,fe:2,mg:55,k2:380,na:280,zn:1.2,fo:40,se:8,col:2}},

{id:'tpl_1099',nome:'Pasta con sugo di carciofi e pancetta',nome_en:'Pasta with artichoke and pancetta sauce',categoria:'Primo piatto',porzioni:4,
note:'Mondare i carciofi e tagliarli. Soffriggere pancetta, aglio e carciofi in olio. Sfumare con vino bianco. Cuocere 15 minuti. Cuocere la pasta al dente. Condire con il sugo, parmigiano e prezzemolo.',
note_en:'Trim artichokes and slice. Sauté pancetta, garlic and artichokes in oil. Deglaze with white wine. Cook 15 minutes. Cook pasta al dente. Dress with sauce, parmesan and parsley.',
ingredienti:[{nome:'Penne rigate',qt:'320g'},{nome:'Carciofi',qt:'4'},{nome:'Pancetta',qt:'80g'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Vino bianco',qt:'80ml'},{nome:'Parmigiano',qt:'40g'},{nome:'Olio extravergine',qt:'40ml'}],
_dbEntry:{n:'Pasta con sugo di carciofi e pancetta (ricetta)',c:'Ricette',src:'RICETTE',k:400,p:17,gs:3,g:11,z:3,ch:58,fi:5,ca:80,fe:2.5,mg:45,k2:380,na:480,zn:1.5,fo:65,se:8,col:20}},

{id:'tpl_1100',nome:'Minestra di farro e fagioli',nome_en:'Farro and bean soup',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere aglio, rosmarino e salvia. Aggiungere fagioli borlotti, farro perlato e brodo. Cuocere 40 minuti. Schiacciare una parte dei fagioli per addensare. Aggiustare di sale. Servire con olio extravergine e pane.',
note_en:'Sauté garlic, rosemary and sage. Add borlotti beans, pearled farro and stock. Cook 40 minutes. Mash some beans to thicken. Season with salt. Serve with extra virgin oil and bread.',
ingredienti:[{nome:'Farro perlato',qt:'200g'},{nome:'Fagioli borlotti cotti',qt:'300g'},{nome:'Aglio',qt:'3 spicchi'},{nome:'Rosmarino',qt:'1 rametto'},{nome:'Salvia',qt:'4 foglie'},{nome:'Brodo vegetale',qt:'1.2L'},{nome:'Olio extravergine',qt:'40ml'}],
_dbEntry:{n:'Minestra di farro e fagioli (ricetta)',c:'Ricette',src:'RICETTE',k:300,p:13,gs:0.5,g:5,z:3,ch:52,fi:10,ca:65,fe:3.5,mg:55,k2:550,na:310,zn:1.5,fo:115,se:6,col:0}},

{id:'tpl_1101',nome:'Pasta con crema di ceci e rosmarino',nome_en:'Pasta with chickpea and rosemary cream',categoria:'Primo piatto',porzioni:4,
note:'Frullare ceci cotti con brodo, rosmarino, aglio e olio fino a crema liscia. Cuocere la pasta al dente. Mantecare con la crema di ceci aggiungendo acqua di cottura. Guarnire con ceci interi soffritti e rosmarino croccante.',
note_en:'Blend cooked chickpeas with stock, rosemary, garlic and oil to smooth cream. Cook pasta al dente. Toss with chickpea cream adding cooking water. Garnish with fried whole chickpeas and crispy rosemary.',
ingredienti:[{nome:'Rigatoni',qt:'320g'},{nome:'Ceci cotti',qt:'400g'},{nome:'Rosmarino',qt:'2 rametti'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Brodo vegetale',qt:'300ml'},{nome:'Olio extravergine',qt:'50ml'}],
_dbEntry:{n:'Pasta con crema di ceci e rosmarino (ricetta)',c:'Ricette',src:'RICETTE',k:380,p:15,gs:1,g:9,z:2,ch:60,fi:9,ca:70,fe:4,mg:60,k2:560,na:240,zn:2,fo:140,se:5,col:0}},

{id:'tpl_1102',nome:'Pasta alla sorrentina veloce',nome_en:'Quick pasta alla sorrentina',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere aglio in olio, aggiungere pomodorini e cuocere 10 minuti. Cuocere la pasta al dente. Scolare e saltare con il sugo. Aggiungere mozzarella a cubetti e basilico. Il calore sciogliera la mozzarella.',
note_en:'Sauté garlic in oil, add cherry tomatoes and cook 10 minutes. Cook pasta al dente. Drain and toss with sauce. Add diced mozzarella and basil. The heat will melt the mozzarella.',
ingredienti:[{nome:'Paccheri',qt:'320g'},{nome:'Pomodorini',qt:'300g'},{nome:'Mozzarella',qt:'200g'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Basilico',qt:'15g'},{nome:'Olio extravergine',qt:'40ml'},{nome:'Parmigiano',qt:'30g'}],
_dbEntry:{n:'Pasta alla sorrentina veloce (ricetta)',c:'Ricette',src:'RICETTE',k:420,p:18,gs:4,g:13,z:4,ch:58,fi:2.5,ca:240,fe:1.5,mg:38,k2:340,na:360,zn:2,fo:35,se:10,col:30}},

{id:'tpl_1103',nome:'Pasta con le fave',nome_en:'Pasta with fava beans',categoria:'Primo piatto',porzioni:4,
note:'Sgranare e spellare le fave. Soffriggere cipollotto, aglio e guanciale. Aggiungere le fave e un poco di brodo. Cuocere la pasta al dente. Condire con il sughetto di fave, pecorino e menta.',
note_en:'Shell and skin fava beans. Sauté spring onion, garlic and guanciale. Add fava beans and a little stock. Cook pasta al dente. Dress with fava bean sauce, pecorino and mint.',
ingredienti:[{nome:'Maccheroni',qt:'320g'},{nome:'Fave fresche sgranate',qt:'400g'},{nome:'Guanciale',qt:'80g'},{nome:'Cipollotto',qt:'2'},{nome:'Pecorino',qt:'50g'},{nome:'Menta fresca',qt:'10g'},{nome:'Olio extravergine',qt:'30ml'}],
_dbEntry:{n:'Pasta con le fave (ricetta)',c:'Ricette',src:'RICETTE',k:400,p:18,gs:3,g:10,z:3,ch:58,fi:8,ca:80,fe:3,mg:55,k2:560,na:420,zn:1.5,fo:160,se:8,col:22}},

{id:'tpl_1104',nome:'Risotto con brie e noci',nome_en:'Risotto with brie and walnuts',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere scalogno in burro. Tostare il riso, sfumare con vino bianco. Aggiungere brodo vegetale. A cottura quasi ultimata aggiungere brie a pezzi senza crosta. Mantecare con burro. Servire con gherigli di noce.',
note_en:'Sauté shallot in butter. Toast rice, deglaze with white wine. Add vegetable stock. Near end of cooking add rindless brie pieces. Stir in butter. Serve with walnut halves.',
ingredienti:[{nome:'Riso Carnaroli',qt:'320g'},{nome:'Brie',qt:'150g'},{nome:'Noci',qt:'50g'},{nome:'Scalogno',qt:'2'},{nome:'Burro',qt:'40g'},{nome:'Vino bianco',qt:'100ml'},{nome:'Brodo vegetale',qt:'1L'}],
_dbEntry:{n:'Risotto con brie e noci (ricetta)',c:'Ricette',src:'RICETTE',k:430,p:14,gs:8,g:18,z:2,ch:54,fi:1.5,ca:160,fe:1.5,mg:30,k2:230,na:450,zn:1.5,fo:25,se:6,col:50}},

{id:'tpl_1105',nome:'Pasta con gamberi e pomodorini',nome_en:'Pasta with prawns and cherry tomatoes',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere aglio in olio, aggiungere gamberi sgusciati. Sfumare con vino bianco. Aggiungere pomodorini tagliati a meta e cuocere 10 minuti. Cuocere la pasta al dente e saltare nel sugo. Aggiungere prezzemolo.',
note_en:'Sauté garlic in oil, add peeled prawns. Deglaze with white wine. Add halved cherry tomatoes and cook 10 minutes. Cook pasta al dente and toss in sauce. Add parsley.',
ingredienti:[{nome:'Linguine',qt:'320g'},{nome:'Gamberi',qt:'300g'},{nome:'Pomodorini',qt:'250g'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Vino bianco',qt:'100ml'},{nome:'Prezzemolo',qt:'15g'},{nome:'Olio extravergine',qt:'40ml'}],
_dbEntry:{n:'Pasta con gamberi e pomodorini (ricetta)',c:'Ricette',src:'RICETTE',k:380,p:20,gs:1.5,g:8,z:3,ch:55,fi:2,ca:60,fe:2.5,mg:45,k2:420,na:340,zn:1.8,fo:35,se:25,col:110}},

{id:'tpl_1106',nome:'Zuppa di fagioli e castagne',nome_en:'Bean and chestnut soup',categoria:'Primo piatto',porzioni:4,
note:'Lessare le castagne. Cuocere i fagioli cannellini con rosmarino e aglio. Unire fagioli, castagne e brodo. Frullare meta. Cuocere 15 minuti. Servire con olio crudo e rametto di rosmarino.',
note_en:'Boil chestnuts. Cook cannellini beans with rosemary and garlic. Combine beans, chestnuts and stock. Blend half. Cook 15 minutes. Serve with raw oil and rosemary sprig.',
ingredienti:[{nome:'Fagioli cannellini cotti',qt:'350g'},{nome:'Castagne cotte',qt:'200g'},{nome:'Rosmarino',qt:'2 rametti'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Brodo vegetale',qt:'800ml'},{nome:'Olio extravergine',qt:'40ml'}],
_dbEntry:{n:'Zuppa di fagioli e castagne (ricetta)',c:'Ricette',src:'RICETTE',k:280,p:10,gs:0.5,g:5,z:4,ch:50,fi:9,ca:60,fe:3,mg:55,k2:580,na:280,zn:1.5,fo:85,se:4,col:0}},

{id:'tpl_1107',nome:'Pasta con le polpette di carne',nome_en:'Pasta with meat meatballs',categoria:'Primo piatto',porzioni:4,
note:'Preparare polpette di macinato misto con uova, parmigiano e prezzemolo. Rosolare le polpette in olio. Preparare sugo di pomodoro. Cuocere le polpette nel sugo 20 minuti. Cuocere gli spaghetti al dente. Servire con polpette e sugo.',
note_en:'Prepare mixed mince meatballs with eggs, parmesan and parsley. Brown meatballs in oil. Make tomato sauce. Cook meatballs in sauce 20 minutes. Cook spaghetti al dente. Serve with meatballs and sauce.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Macinato misto',qt:'400g'},{nome:'Uova',qt:'2'},{nome:'Parmigiano',qt:'50g'},{nome:'Pomodori pelati',qt:'400g'},{nome:'Prezzemolo',qt:'15g'},{nome:'Olio extravergine',qt:'40ml'}],
_dbEntry:{n:'Pasta con le polpette di carne (ricetta)',c:'Ricette',src:'RICETTE',k:450,p:26,gs:4,g:14,z:5,ch:55,fi:2.5,ca:110,fe:3,mg:42,k2:500,na:400,zn:4,fo:40,se:20,col:100}},

{id:'tpl_1108',nome:'Pasta fredda con verdure grigliate',nome_en:'Cold pasta with grilled vegetables',categoria:'Primo piatto',porzioni:4,
note:'Grigliare zucchine, melanzane e peperoni. Tagliare a pezzi e marinare con olio, aglio e basilico. Cuocere la pasta al dente, sciacquare in acqua fredda. Mescolare con le verdure grigliate e olive.',
note_en:'Grill courgettes, aubergines and peppers. Cut into pieces and marinate with oil, garlic and basil. Cook pasta al dente, rinse in cold water. Mix with grilled vegetables and olives.',
ingredienti:[{nome:'Fusilli',qt:'320g'},{nome:'Zucchine',qt:'200g'},{nome:'Melanzane',qt:'200g'},{nome:'Peperoni',qt:'2'},{nome:'Olive',qt:'60g'},{nome:'Aglio',qt:'2 spicchi'},{nome:'Olio extravergine',qt:'50ml'},{nome:'Basilico',qt:'15g'}],
_dbEntry:{n:'Pasta fredda con verdure grigliate (ricetta)',c:'Ricette',src:'RICETTE',k:390,p:11,gs:1.5,g:12,z:5,ch:60,fi:5,ca:55,fe:2,mg:45,k2:420,na:300,zn:1,fo:55,se:6,col:0}},

{id:'tpl_1109',nome:'Risotto al pomodoro e basilico',nome_en:'Tomato and basil risotto',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere cipolla in olio. Tostare il riso, sfumare con vino bianco. Aggiungere brodo caldo e passata di pomodoro. Cuocere 18 minuti. Mantecare con burro, parmigiano e basilico fresco.',
note_en:'Sauté onion in oil. Toast rice, deglaze with white wine. Add hot stock and tomato passata. Cook 18 minutes. Stir in butter, parmesan and fresh basil.',
ingredienti:[{nome:'Riso Carnaroli',qt:'320g'},{nome:'Passata di pomodoro',qt:'300g'},{nome:'Cipolla',qt:'1'},{nome:'Basilico',qt:'15g'},{nome:'Burro',qt:'40g'},{nome:'Parmigiano',qt:'50g'},{nome:'Vino bianco',qt:'100ml'},{nome:'Brodo vegetale',qt:'700ml'}],
_dbEntry:{n:'Risotto al pomodoro e basilico (ricetta)',c:'Ricette',src:'RICETTE',k:380,p:11,gs:4,g:9,z:5,ch:62,fi:2.5,ca:90,fe:1.5,mg:30,k2:380,na:320,zn:1,fo:28,se:7,col:25}},

{id:'tpl_1110',nome:'Pasta con sugo di cinghiale',nome_en:'Pasta with wild boar sauce',categoria:'Primo piatto',porzioni:4,
note:'Marinare il cinghiale con vino rosso e aromi. Rosolare con soffritto. Sfumare con la marinatura filtrata. Aggiungere pomodoro e cuocere 2 ore. Cuocere i pici o le pappardelle. Condire con il ragu.',
note_en:'Marinate wild boar with red wine and aromatics. Brown with soffritto. Deglaze with strained marinade. Add tomato and cook 2 hours. Cook pici or pappardelle. Dress with ragu.',
ingredienti:[{nome:'Pappardelle',qt:'320g'},{nome:'Cinghiale',qt:'500g'},{nome:'Vino rosso',qt:'300ml'},{nome:'Pomodori pelati',qt:'400g'},{nome:'Cipolla',qt:'1'},{nome:'Carota',qt:'1'},{nome:'Sedano',qt:'1 costa'},{nome:'Rosmarino',qt:'q.b.'}],
_dbEntry:{n:'Pasta con sugo di cinghiale (ricetta)',c:'Ricette',src:'RICETTE',k:440,p:28,gs:4,g:12,z:4,ch:52,fi:2.5,ca:60,fe:3.5,mg:38,k2:500,na:380,zn:4.5,fo:40,se:18,col:75}},

{id:'tpl_1111',nome:'Pasta con pesto di rucola e noci',nome_en:'Pasta with rocket and walnut pesto',categoria:'Primo piatto',porzioni:4,
note:'Frullare rucola, noci, parmigiano, aglio e olio per creare il pesto. Cuocere le farfalle al dente. Mantecare con il pesto e acqua di cottura. Guarnire con pomodorini e scaglie di parmigiano.',
note_en:'Blend rocket, walnuts, parmesan, garlic and oil to make pesto. Cook farfalle al dente. Toss with pesto and cooking water. Garnish with cherry tomatoes and parmesan shavings.',
ingredienti:[{nome:'Farfalle',qt:'320g'},{nome:'Rucola',qt:'100g'},{nome:'Noci',qt:'50g'},{nome:'Parmigiano',qt:'50g'},{nome:'Aglio',qt:'1 spicchio'},{nome:'Olio extravergine',qt:'70ml'},{nome:'Pomodorini',qt:'100g'}],
_dbEntry:{n:'Pasta con pesto di rucola e noci (ricetta)',c:'Ricette',src:'RICETTE',k:450,p:15,gs:3,g:19,z:3,ch:57,fi:2.5,ca:120,fe:2.5,mg:50,k2:340,na:220,zn:1.5,fo:50,se:8,col:5}},

{id:'tpl_1112',nome:'Vellutata di funghi e timo',nome_en:'Mushroom and thyme velouté',categoria:'Primo piatto',porzioni:4,
note:'Soffriggere scalogno in burro. Aggiungere funghi misti tagliati e timo. Versare brodo e panna. Cuocere 20 minuti. Frullare fino a velluto. Aggiustare di sale. Servire con funghi trifolati e crostini.',
note_en:'Sauté shallot in butter. Add sliced mixed mushrooms and thyme. Pour in stock and cream. Cook 20 minutes. Blend to velvet. Season with salt. Serve with trifolati mushrooms and croutons.',
ingredienti:[{nome:'Funghi misti',qt:'500g'},{nome:'Scalogno',qt:'2'},{nome:'Timo',qt:'4 rametti'},{nome:'Panna da cucina',qt:'100ml'},{nome:'Brodo vegetale',qt:'500ml'},{nome:'Burro',qt:'30g'},{nome:'Pane per crostini',qt:'80g'}],
_dbEntry:{n:'Vellutata di funghi e timo (ricetta)',c:'Ricette',src:'RICETTE',k:220,p:5,gs:5,g:12,z:3,ch:22,fi:3.5,ca:40,fe:2,mg:25,k2:450,na:350,zn:1,fo:30,se:8,col:40}},

{id:'tpl_1113',nome:'Pasta con ricotta e limone',nome_en:'Pasta with ricotta and lemon',categoria:'Primo piatto',porzioni:4,
note:'Amalgamare ricotta con scorza e succo di limone, parmigiano, sale e pepe. Cuocere i fusilli al dente. Scolare tenendo acqua di cottura. Mantecare con la crema di ricotta aggiungendo acqua per ammorbidire. Guarnire con foglie di basilico.',
note_en:'Mix ricotta with lemon zest and juice, parmesan, salt and pepper. Cook fusilli al dente. Drain keeping cooking water. Toss with ricotta cream adding water to soften. Garnish with basil leaves.',
ingredienti:[{nome:'Fusilli',qt:'320g'},{nome:'Ricotta',qt:'200g'},{nome:'Limone',qt:'2'},{nome:'Parmigiano',qt:'40g'},{nome:'Basilico',qt:'10g'}],
_dbEntry:{n:'Pasta con ricotta e limone (ricetta)',c:'Ricette',src:'RICETTE',k:380,p:16,gs:3,g:9,z:4,ch:60,fi:2,ca:160,fe:1.5,mg:30,k2:250,na:180,zn:1.2,fo:35,se:8,col:25}},

{id:'tpl_1114',nome:'Zuppa di coda di bue',nome_en:'Oxtail soup',categoria:'Primo piatto',porzioni:4,
note:'Rosolare la coda a pezzi con verdure. Sfumare con vino rosso. Aggiungere brodo e cuocere 3 ore a fuoco lento. Disossare la coda e rimettere la carne nel brodo. Aggiustare di sale e servire con pasta corta.',
note_en:'Brown oxtail pieces with vegetables. Deglaze with red wine. Add stock and cook 3 hours on low heat. Debone oxtail and return meat to broth. Season with salt and serve with short pasta.',
ingredienti:[{nome:'Coda di bue',qt:'800g'},{nome:'Pasta corta',qt:'120g'},{nome:'Cipolla',qt:'1'},{nome:'Carota',qt:'2'},{nome:'Sedano',qt:'2 coste'},{nome:'Vino rosso',qt:'200ml'},{nome:'Brodo di carne',qt:'1L'}],
_dbEntry:{n:'Zuppa di coda di bue (ricetta)',c:'Ricette',src:'RICETTE',k:320,p:24,gs:4,g:11,z:3,ch:28,fi:2,ca:55,fe:3,mg:30,k2:420,na:420,zn:5,fo:20,se:15,col:90}},

{id:'tpl_1115',nome:'Pasta e fagioli con le cotiche',nome_en:'Pasta and beans with pork rind',categoria:'Primo piatto',porzioni:4,
note:'Sbollentare le cotiche e tagliarle a listarelle. Soffriggere cipolla, aglio e lardo. Aggiungere cotiche, fagioli borlotti e pomodori. Versare brodo e cuocere 1 ora. Aggiungere pasta mista e finire.',
note_en:'Blanch pork rind and cut into strips. Sauté onion, garlic and lard. Add pork rind, borlotti beans and tomatoes. Pour in stock and cook 1 hour. Add mixed pasta and finish.',
ingredienti:[{nome:'Pasta mista',qt:'200g'},{nome:'Fagioli borlotti',qt:'300g'},{nome:'Cotiche di maiale',qt:'150g'},{nome:'Lardo',qt:'50g'},{nome:'Pomodori pelati',qt:'200g'},{nome:'Cipolla',qt:'1'},{nome:'Brodo',qt:'800ml'}],
_dbEntry:{n:'Pasta e fagioli con le cotiche (ricetta)',c:'Ricette',src:'RICETTE',k:380,p:20,gs:4,g:12,z:3,ch:50,fi:8,ca:70,fe:3.5,mg:55,k2:580,na:500,zn:2.5,fo:105,se:8,col:35}},

{id:'tpl_1116',nome:'Pasta al forno con carne e bechamel',nome_en:'Baked pasta with meat and bechamel',categoria:'Primo piatto',porzioni:6,
note:'Preparare ragu di carne. Preparare besciamella. Cuocere la pasta al dente. In una teglia alternare strati di pasta, ragu e besciamella. Aggiungere parmigiano. Cuocere in forno a 180 C per 35 minuti.',
note_en:'Make meat ragu. Make bechamel. Cook pasta al dente. In a baking dish alternate layers of pasta, ragu and bechamel. Add parmesan. Bake at 180 C for 35 minutes.',
ingredienti:[{nome:'Maccheroni',qt:'400g'},{nome:'Macinato di manzo',qt:'400g'},{nome:'Latte',qt:'500ml'},{nome:'Farina',qt:'50g'},{nome:'Burro',qt:'50g'},{nome:'Parmigiano',qt:'80g'},{nome:'Pomodori pelati',qt:'400g'},{nome:'Cipolla',qt:'1'}],
_dbEntry:{n:'Pasta al forno con carne e bechamel (ricetta)',c:'Ricette',src:'RICETTE',k:400,p:22,gs:5,g:14,z:4,ch:50,fi:2.5,ca:200,fe:2.5,mg:35,k2:450,na:480,zn:3,fo:35,se:18,col:80}},

{id:'tpl_1117',nome:'Pasta con sugo di verdure arrostite',nome_en:'Pasta with roasted vegetable sauce',categoria:'Primo piatto',porzioni:4,
note:'Arrostire melanzane, zucchine e peperoni in forno con olio. Frullare meta per fare la base del sugo. Soffriggere aglio, aggiungere il sugo e le verdure a pezzi. Cuocere la pasta e saltare nel sugo.',
note_en:'Roast aubergines, courgettes and peppers in oven with oil. Blend half for sauce base. Sauté garlic, add sauce and vegetable pieces. Cook pasta and toss in sauce.',
ingredienti:[{nome:'Pasta corta',qt:'320g'},{nome:'Melanzane',qt:'200g'},{nome:'Zucchine',qt:'200g'},{nome:'Peperoni',qt:'2'},{nome:'Aglio',qt:'3 spicchi'},{nome:'Olio extravergine',qt:'50ml'},{nome:'Basilico',qt:'15g'}],
_dbEntry:{n:'Pasta con sugo di verdure arrostite (ricetta)',c:'Ricette',src:'RICETTE',k:380,p:11,gs:1.5,g:10,z:6,ch:60,fi:5.5,ca:50,fe:2,mg:45,k2:480,na:200,zn:1,fo:55,se:7,col:0}},

{id:'tpl_1118',nome:'Pasta alla crema di parmigiano',nome_en:'Pasta with parmesan cream',categoria:'Primo piatto',porzioni:4,
note:'Sciogliere parmigiano grattugiato con acqua calda di cottura della pasta e olio extravergine fino a crema. Cuocere la pasta al dente. Mantecare con la crema di parmigiano fuori dal fuoco. Aggiungere pepe nero abbondante.',
note_en:'Dissolve grated parmesan with hot pasta cooking water and extra virgin oil until creamy. Cook pasta al dente. Toss off heat with parmesan cream. Add plenty of black pepper.',
ingredienti:[{nome:'Spaghetti',qt:'320g'},{nome:'Parmigiano grattugiato',qt:'120g'},{nome:'Olio extravergine',qt:'40ml'},{nome:'Pepe nero',qt:'q.b.'}],
_dbEntry:{n:'Pasta alla crema di parmigiano (ricetta)',c:'Ricette',src:'RICETTE',k:420,p:18,gs:5,g:13,z:2,ch:58,fi:1,ca:350,fe:1.5,mg:30,k2:180,na:420,zn:2.5,fo:15,se:8,col:28}},

{id:'tpl_1119',nome:'Minestrone invernale con legumi',nome_en:'Winter minestrone with legumes',categoria:'Primo piatto',porzioni:6,
note:'Soffriggere sedano, cipolla e carota. Aggiungere cavolo, broccoli, fagioli, lenticchie e brodo. Cuocere 35 minuti. Aggiungere pasta corta. Servire con parmigiano e olio crudo.',
note_en:'Sauté celery, onion and carrot. Add cabbage, broccoli, beans, lentils and stock. Cook 35 minutes. Add short pasta. Serve with parmesan and raw oil.',
ingredienti:[{nome:'Pasta corta',qt:'160g'},{nome:'Fagioli misti cotti',qt:'300g'},{nome:'Lenticchie cotte',qt:'150g'},{nome:'Cavolo',qt:'200g'},{nome:'Broccoli',qt:'200g'},{nome:'Carota',qt:'2'},{nome:'Cipolla',qt:'1'},{nome:'Brodo vegetale',qt:'1.5L'}],
_dbEntry:{n:'Minestrone invernale con legumi (ricetta)',c:'Ricette',src:'RICETTE',k:280,p:13,gs:0.5,g:5,z:4,ch:46,fi:11,ca:80,fe:3.5,mg:60,k2:600,na:340,zn:1.8,fo:130,se:5,col:0}},

{id:'tpl_1120',nome:'Pasta con sugo alle noci e panna',nome_en:'Pasta with walnut and cream sauce',categoria:'Primo piatto',porzioni:4,
note:'Tostare le noci in padella. Frullarle con aglio, parmigiano e panna per fare la salsa. Cuocere i rigatoni al dente. Mantecare con la salsa di noci aggiungendo acqua di cottura. Guarnire con noci intere.',
note_en:'Toast walnuts in pan. Blend with garlic, parmesan and cream to make sauce. Cook rigatoni al dente. Toss with walnut sauce adding cooking water. Garnish with whole walnuts.',
ingredienti:[{nome:'Rigatoni',qt:'320g'},{nome:'Noci',qt:'100g'},{nome:'Panna da cucina',qt:'80ml'},{nome:'Parmigiano',qt:'50g'},{nome:'Aglio',qt:'1 spicchio'},{nome:'Olio extravergine',qt:'20ml'}],
_dbEntry:{n:'Pasta con sugo alle noci e panna (ricetta)',c:'Ricette',src:'RICETTE',k:470,p:16,gs:5,g:21,z:3,ch:55,fi:2.5,ca:130,fe:1.5,mg:45,k2:280,na:250,zn:1.5,fo:25,se:7,col:28}},

];
if (typeof rebuildDB === 'function') rebuildDB();
